insert into category (id, name) values (1, 'Framing (Steel)');
insert into category (id, name) values (2, 'Wall Protection');
insert into category (id, name) values (3, 'Electrical');
insert into category (id, name) values (4, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (5, 'Waterproofing & Caulking');
insert into category (id, name) values (6, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (7, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (8, 'Drilled Shafts');
insert into category (id, name) values (9, 'Termite Control');
insert into category (id, name) values (10, 'Exterior Signage');
insert into category (id, name) values (11, 'HVAC');
insert into category (id, name) values (12, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (13, 'Roofing (Metal)');
insert into category (id, name) values (14, 'Electrical');
insert into category (id, name) values (15, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (16, 'Termite Control');
insert into category (id, name) values (17, 'Structural & Misc Steel Erection');
insert into category (id, name) values (18, 'Termite Control');
insert into category (id, name) values (19, 'Waterproofing & Caulking');
insert into category (id, name) values (20, 'Doors, Frames & Hardware');
insert into category (id, name) values (21, 'Elevator');
insert into category (id, name) values (22, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (23, 'Framing (Steel)');
insert into category (id, name) values (24, 'Hard Tile & Stone');
insert into category (id, name) values (25, 'Electrical and Fire Alarm');
insert into category (id, name) values (26, 'Sitework & Site Utilities');
insert into category (id, name) values (27, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (28, 'RF Shielding');
insert into category (id, name) values (29, 'Casework');
insert into category (id, name) values (30, 'Doors, Frames & Hardware');
insert into category (id, name) values (31, 'Marlite Panels (FED)');
insert into category (id, name) values (32, 'Roofing (Asphalt)');
insert into category (id, name) values (33, 'Hard Tile & Stone');
insert into category (id, name) values (34, 'Site Furnishings');
insert into category (id, name) values (35, 'Overhead Doors');
insert into category (id, name) values (36, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (37, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (38, 'Epoxy Flooring');
insert into category (id, name) values (39, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (40, 'Masonry & Precast');
insert into category (id, name) values (41, 'Roofing (Metal)');
insert into category (id, name) values (42, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (43, 'Electrical and Fire Alarm');
insert into category (id, name) values (44, 'Asphalt Paving');
insert into category (id, name) values (45, 'Doors, Frames & Hardware');
insert into category (id, name) values (46, 'Drilled Shafts');
insert into category (id, name) values (47, 'Drilled Shafts');
insert into category (id, name) values (48, 'Hard Tile & Stone');
insert into category (id, name) values (49, 'Termite Control');
insert into category (id, name) values (50, 'Elevator');
insert into category (id, name) values (51, 'Glass & Glazing');
insert into category (id, name) values (52, 'Masonry & Precast');
insert into category (id, name) values (53, 'Framing (Wood)');
insert into category (id, name) values (54, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (55, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (56, 'Overhead Doors');
insert into category (id, name) values (57, 'Asphalt Paving');
insert into category (id, name) values (58, 'Termite Control');
insert into category (id, name) values (59, 'Landscaping & Irrigation');
insert into category (id, name) values (60, 'Termite Control');
insert into category (id, name) values (61, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (62, 'Fire Sprinkler System');
insert into category (id, name) values (63, 'Framing (Steel)');
insert into category (id, name) values (64, 'Drilled Shafts');
insert into category (id, name) values (65, 'Masonry & Precast');
insert into category (id, name) values (66, 'Glass & Glazing');
insert into category (id, name) values (67, 'Roofing (Asphalt)');
insert into category (id, name) values (68, 'Wall Protection');
insert into category (id, name) values (69, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (70, 'Framing (Wood)');
insert into category (id, name) values (71, 'Framing (Wood)');
insert into category (id, name) values (72, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (73, 'Asphalt Paving');
insert into category (id, name) values (74, 'Marlite Panels (FED)');
insert into category (id, name) values (75, 'Elevator');
insert into category (id, name) values (76, 'Casework');
insert into category (id, name) values (77, 'Ornamental Railings');
insert into category (id, name) values (78, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (79, 'Structural & Misc Steel Erection');
insert into category (id, name) values (80, 'Structural & Misc Steel Erection');
insert into category (id, name) values (81, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (82, 'Roofing (Metal)');
insert into category (id, name) values (83, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (84, 'Marlite Panels (FED)');
insert into category (id, name) values (85, 'Casework');
insert into category (id, name) values (86, 'Roofing (Metal)');
insert into category (id, name) values (87, 'Doors, Frames & Hardware');
insert into category (id, name) values (88, 'Glass & Glazing');
insert into category (id, name) values (89, 'Ornamental Railings');
insert into category (id, name) values (90, 'Construction Clean and Final Clean');
insert into category (id, name) values (91, 'Epoxy Flooring');
insert into category (id, name) values (92, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (93, 'Framing (Steel)');
insert into category (id, name) values (94, 'Ornamental Railings');
insert into category (id, name) values (95, 'Electrical');
insert into category (id, name) values (96, 'Electrical');
insert into category (id, name) values (97, 'Framing (Wood)');
insert into category (id, name) values (98, 'Epoxy Flooring');
insert into category (id, name) values (99, 'Overhead Doors');
insert into category (id, name) values (100, 'Roofing (Metal)');
insert into category (id, name) values (101, 'Plumbing & Medical Gas');
insert into category (id, name) values (102, 'Drilled Shafts');
insert into category (id, name) values (103, 'Waterproofing & Caulking');
insert into category (id, name) values (104, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (105, 'Plumbing & Medical Gas');
insert into category (id, name) values (106, 'Overhead Doors');
insert into category (id, name) values (107, 'Drilled Shafts');
insert into category (id, name) values (108, 'Masonry');
insert into category (id, name) values (109, 'EIFS');
insert into category (id, name) values (110, 'Elevator');
insert into category (id, name) values (111, 'Masonry');
insert into category (id, name) values (112, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (113, 'Wall Protection');
insert into category (id, name) values (114, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (115, 'Framing (Wood)');
insert into category (id, name) values (116, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (117, 'Masonry & Precast');
insert into category (id, name) values (118, 'HVAC');
insert into category (id, name) values (119, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (120, 'Overhead Doors');
insert into category (id, name) values (121, 'Exterior Signage');
insert into category (id, name) values (122, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (123, 'Asphalt Paving');
insert into category (id, name) values (124, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (125, 'Hard Tile & Stone');
insert into category (id, name) values (126, 'Electrical');
insert into category (id, name) values (127, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (128, 'Marlite Panels (FED)');
insert into category (id, name) values (129, 'Framing (Wood)');
insert into category (id, name) values (130, 'RF Shielding');
insert into category (id, name) values (131, 'Construction Clean and Final Clean');
insert into category (id, name) values (132, 'Landscaping & Irrigation');
insert into category (id, name) values (133, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (134, 'Marlite Panels (FED)');
insert into category (id, name) values (135, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (136, 'Exterior Signage');
insert into category (id, name) values (137, 'Glass & Glazing');
insert into category (id, name) values (138, 'Termite Control');
insert into category (id, name) values (139, 'Construction Clean and Final Clean');
insert into category (id, name) values (140, 'Site Furnishings');
insert into category (id, name) values (141, 'EIFS');
insert into category (id, name) values (142, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (143, 'Epoxy Flooring');
insert into category (id, name) values (144, 'Masonry');
insert into category (id, name) values (145, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (146, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (147, 'Marlite Panels (FED)');
insert into category (id, name) values (148, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (149, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (150, 'Doors, Frames & Hardware');
insert into category (id, name) values (151, 'Structural & Misc Steel Erection');
insert into category (id, name) values (152, 'Exterior Signage');
insert into category (id, name) values (153, 'Ornamental Railings');
insert into category (id, name) values (154, 'Waterproofing & Caulking');
insert into category (id, name) values (155, 'Framing (Steel)');
insert into category (id, name) values (156, 'Ornamental Railings');
insert into category (id, name) values (157, 'Roofing (Asphalt)');
insert into category (id, name) values (158, 'Electrical');
insert into category (id, name) values (159, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (160, 'Overhead Doors');
insert into category (id, name) values (161, 'Drilled Shafts');
insert into category (id, name) values (162, 'Electrical and Fire Alarm');
insert into category (id, name) values (163, 'Granite Surfaces');
insert into category (id, name) values (164, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (165, 'Overhead Doors');
insert into category (id, name) values (166, 'Construction Clean and Final Clean');
insert into category (id, name) values (167, 'HVAC');
insert into category (id, name) values (168, 'Roofing (Asphalt)');
insert into category (id, name) values (169, 'Marlite Panels (FED)');
insert into category (id, name) values (170, 'Marlite Panels (FED)');
insert into category (id, name) values (171, 'Construction Clean and Final Clean');
insert into category (id, name) values (172, 'Landscaping & Irrigation');
insert into category (id, name) values (173, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (174, 'Masonry');
insert into category (id, name) values (175, 'Doors, Frames & Hardware');
insert into category (id, name) values (176, 'Curb & Gutter');
insert into category (id, name) values (177, 'Marlite Panels (FED)');
insert into category (id, name) values (178, 'Electrical and Fire Alarm');
insert into category (id, name) values (179, 'Ornamental Railings');
insert into category (id, name) values (180, 'Framing (Wood)');
insert into category (id, name) values (181, 'Hard Tile & Stone');
insert into category (id, name) values (182, 'EIFS');
insert into category (id, name) values (183, 'Asphalt Paving');
insert into category (id, name) values (184, 'Roofing (Asphalt)');
insert into category (id, name) values (185, 'Glass & Glazing');
insert into category (id, name) values (186, 'Roofing (Asphalt)');
insert into category (id, name) values (187, 'HVAC');
insert into category (id, name) values (188, 'Ornamental Railings');
insert into category (id, name) values (189, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (190, 'Plumbing & Medical Gas');
insert into category (id, name) values (191, 'HVAC');
insert into category (id, name) values (192, 'Waterproofing & Caulking');
insert into category (id, name) values (193, 'Structural & Misc Steel Erection');
insert into category (id, name) values (194, 'Plumbing & Medical Gas');
insert into category (id, name) values (195, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (196, 'Hard Tile & Stone');
insert into category (id, name) values (197, 'Curb & Gutter');
insert into category (id, name) values (198, 'Wall Protection');
insert into category (id, name) values (199, 'Electrical and Fire Alarm');
insert into category (id, name) values (200, 'Structural & Misc Steel Erection');
insert into category (id, name) values (201, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (202, 'HVAC');
insert into category (id, name) values (203, 'Elevator');
insert into category (id, name) values (204, 'Plumbing & Medical Gas');
insert into category (id, name) values (205, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (206, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (207, 'Overhead Doors');
insert into category (id, name) values (208, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (209, 'Structural & Misc Steel Erection');
insert into category (id, name) values (210, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (211, 'Exterior Signage');
insert into category (id, name) values (212, 'Framing (Wood)');
insert into category (id, name) values (213, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (214, 'Electrical');
insert into category (id, name) values (215, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (216, 'Elevator');
insert into category (id, name) values (217, 'Soft Flooring and Base');
insert into category (id, name) values (218, 'Hard Tile & Stone');
insert into category (id, name) values (219, 'Drilled Shafts');
insert into category (id, name) values (220, 'Masonry');
insert into category (id, name) values (221, 'Asphalt Paving');
insert into category (id, name) values (222, 'Framing (Wood)');
insert into category (id, name) values (223, 'Fire Sprinkler System');
insert into category (id, name) values (224, 'Roofing (Asphalt)');
insert into category (id, name) values (225, 'Fire Protection');
insert into category (id, name) values (226, 'Doors, Frames & Hardware');
insert into category (id, name) values (227, 'Granite Surfaces');
insert into category (id, name) values (228, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (229, 'Elevator');
insert into category (id, name) values (230, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (231, 'Site Furnishings');
insert into category (id, name) values (232, 'Casework');
insert into category (id, name) values (233, 'Sitework & Site Utilities');
insert into category (id, name) values (234, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (235, 'Epoxy Flooring');
insert into category (id, name) values (236, 'Fire Sprinkler System');
insert into category (id, name) values (237, 'Construction Clean and Final Clean');
insert into category (id, name) values (238, 'Soft Flooring and Base');
insert into category (id, name) values (239, 'HVAC');
insert into category (id, name) values (240, 'EIFS');
insert into category (id, name) values (241, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (242, 'Drilled Shafts');
insert into category (id, name) values (243, 'Structural & Misc Steel Erection');
insert into category (id, name) values (244, 'Glass & Glazing');
insert into category (id, name) values (245, 'Electrical');
insert into category (id, name) values (246, 'Masonry');
insert into category (id, name) values (247, 'Wall Protection');
insert into category (id, name) values (248, 'Marlite Panels (FED)');
insert into category (id, name) values (249, 'Fire Protection');
insert into category (id, name) values (250, 'Hard Tile & Stone');
insert into category (id, name) values (251, 'Asphalt Paving');
insert into category (id, name) values (252, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (253, 'Construction Clean and Final Clean');
insert into category (id, name) values (254, 'Waterproofing & Caulking');
insert into category (id, name) values (255, 'Ornamental Railings');
insert into category (id, name) values (256, 'Framing (Steel)');
insert into category (id, name) values (257, 'Termite Control');
insert into category (id, name) values (258, 'Elevator');
insert into category (id, name) values (259, 'Termite Control');
insert into category (id, name) values (260, 'Doors, Frames & Hardware');
insert into category (id, name) values (261, 'Fire Sprinkler System');
insert into category (id, name) values (262, 'Asphalt Paving');
insert into category (id, name) values (263, 'Construction Clean and Final Clean');
insert into category (id, name) values (264, 'Wall Protection');
insert into category (id, name) values (265, 'Structural & Misc Steel Erection');
insert into category (id, name) values (266, 'EIFS');
insert into category (id, name) values (267, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (268, 'Construction Clean and Final Clean');
insert into category (id, name) values (269, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (270, 'Masonry & Precast');
insert into category (id, name) values (271, 'Soft Flooring and Base');
insert into category (id, name) values (272, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (273, 'Masonry & Precast');
insert into category (id, name) values (274, 'Waterproofing & Caulking');
insert into category (id, name) values (275, 'Electrical');
insert into category (id, name) values (276, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (277, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (278, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (279, 'Doors, Frames & Hardware');
insert into category (id, name) values (280, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (281, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (282, 'Curb & Gutter');
insert into category (id, name) values (283, 'Sitework & Site Utilities');
insert into category (id, name) values (284, 'Exterior Signage');
insert into category (id, name) values (285, 'Elevator');
insert into category (id, name) values (286, 'Elevator');
insert into category (id, name) values (287, 'Epoxy Flooring');
insert into category (id, name) values (288, 'Marlite Panels (FED)');
insert into category (id, name) values (289, 'Glass & Glazing');
insert into category (id, name) values (290, 'Glass & Glazing');
insert into category (id, name) values (291, 'Hard Tile & Stone');
insert into category (id, name) values (292, 'Wall Protection');
insert into category (id, name) values (293, 'Fire Protection');
insert into category (id, name) values (294, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (295, 'Fire Protection');
insert into category (id, name) values (296, 'Masonry & Precast');
insert into category (id, name) values (297, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (298, 'Marlite Panels (FED)');
insert into category (id, name) values (299, 'EIFS');
insert into category (id, name) values (300, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (301, 'Electrical');
insert into category (id, name) values (302, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (303, 'Overhead Doors');
insert into category (id, name) values (304, 'Fire Sprinkler System');
insert into category (id, name) values (305, 'RF Shielding');
insert into category (id, name) values (306, 'Roofing (Asphalt)');
insert into category (id, name) values (307, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (308, 'Casework');
insert into category (id, name) values (309, 'Curb & Gutter');
insert into category (id, name) values (310, 'Granite Surfaces');
insert into category (id, name) values (311, 'Soft Flooring and Base');
insert into category (id, name) values (312, 'Exterior Signage');
insert into category (id, name) values (313, 'Granite Surfaces');
insert into category (id, name) values (314, 'Granite Surfaces');
insert into category (id, name) values (315, 'Plumbing & Medical Gas');
insert into category (id, name) values (316, 'Roofing (Metal)');
insert into category (id, name) values (317, 'Structural & Misc Steel Erection');
insert into category (id, name) values (318, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (319, 'EIFS');
insert into category (id, name) values (320, 'Framing (Wood)');
insert into category (id, name) values (321, 'Granite Surfaces');
insert into category (id, name) values (322, 'Wall Protection');
insert into category (id, name) values (323, 'Wall Protection');
insert into category (id, name) values (324, 'EIFS');
insert into category (id, name) values (325, 'Plumbing & Medical Gas');
insert into category (id, name) values (326, 'Framing (Wood)');
insert into category (id, name) values (327, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (328, 'Wall Protection');
insert into category (id, name) values (329, 'Exterior Signage');
insert into category (id, name) values (330, 'Fire Protection');
insert into category (id, name) values (331, 'Casework');
insert into category (id, name) values (332, 'Casework');
insert into category (id, name) values (333, 'Hard Tile & Stone');
insert into category (id, name) values (334, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (335, 'Asphalt Paving');
insert into category (id, name) values (336, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (337, 'Masonry & Precast');
insert into category (id, name) values (338, 'Soft Flooring and Base');
insert into category (id, name) values (339, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (340, 'Electrical');
insert into category (id, name) values (341, 'Roofing (Metal)');
insert into category (id, name) values (342, 'Granite Surfaces');
insert into category (id, name) values (343, 'Electrical');
insert into category (id, name) values (344, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (345, 'Hard Tile & Stone');
insert into category (id, name) values (346, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (347, 'Exterior Signage');
insert into category (id, name) values (348, 'Asphalt Paving');
insert into category (id, name) values (349, 'Roofing (Asphalt)');
insert into category (id, name) values (350, 'Elevator');
insert into category (id, name) values (351, 'Structural & Misc Steel Erection');
insert into category (id, name) values (352, 'Doors, Frames & Hardware');
insert into category (id, name) values (353, 'Doors, Frames & Hardware');
insert into category (id, name) values (354, 'Soft Flooring and Base');
insert into category (id, name) values (355, 'Waterproofing & Caulking');
insert into category (id, name) values (356, 'Doors, Frames & Hardware');
insert into category (id, name) values (357, 'Termite Control');
insert into category (id, name) values (358, 'Structural & Misc Steel Erection');
insert into category (id, name) values (359, 'Site Furnishings');
insert into category (id, name) values (360, 'Drilled Shafts');
insert into category (id, name) values (361, 'Ornamental Railings');
insert into category (id, name) values (362, 'Plumbing & Medical Gas');
insert into category (id, name) values (363, 'Elevator');
insert into category (id, name) values (364, 'Marlite Panels (FED)');
insert into category (id, name) values (365, 'Construction Clean and Final Clean');
insert into category (id, name) values (366, 'Framing (Wood)');
insert into category (id, name) values (367, 'Elevator');
insert into category (id, name) values (368, 'Roofing (Asphalt)');
insert into category (id, name) values (369, 'Electrical');
insert into category (id, name) values (370, 'Electrical and Fire Alarm');
insert into category (id, name) values (371, 'Site Furnishings');
insert into category (id, name) values (372, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (373, 'Masonry & Precast');
insert into category (id, name) values (374, 'Overhead Doors');
insert into category (id, name) values (375, 'Casework');
insert into category (id, name) values (376, 'Roofing (Metal)');
insert into category (id, name) values (377, 'Fire Protection');
insert into category (id, name) values (378, 'Site Furnishings');
insert into category (id, name) values (379, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (380, 'Landscaping & Irrigation');
insert into category (id, name) values (381, 'Exterior Signage');
insert into category (id, name) values (382, 'Sitework & Site Utilities');
insert into category (id, name) values (383, 'Termite Control');
insert into category (id, name) values (384, 'Elevator');
insert into category (id, name) values (385, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (386, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (387, 'Elevator');
insert into category (id, name) values (388, 'Marlite Panels (FED)');
insert into category (id, name) values (389, 'HVAC');
insert into category (id, name) values (390, 'HVAC');
insert into category (id, name) values (391, 'Roofing (Asphalt)');
insert into category (id, name) values (392, 'Wall Protection');
insert into category (id, name) values (393, 'Exterior Signage');
insert into category (id, name) values (394, 'Glass & Glazing');
insert into category (id, name) values (395, 'HVAC');
insert into category (id, name) values (396, 'Overhead Doors');
insert into category (id, name) values (397, 'Wall Protection');
insert into category (id, name) values (398, 'Glass & Glazing');
insert into category (id, name) values (399, 'Epoxy Flooring');
insert into category (id, name) values (400, 'Fire Sprinkler System');
insert into category (id, name) values (401, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (402, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (403, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (404, 'Epoxy Flooring');
insert into category (id, name) values (405, 'Drilled Shafts');
insert into category (id, name) values (406, 'Plumbing & Medical Gas');
insert into category (id, name) values (407, 'Framing (Steel)');
insert into category (id, name) values (408, 'Curb & Gutter');
insert into category (id, name) values (409, 'Sitework & Site Utilities');
insert into category (id, name) values (410, 'Asphalt Paving');
insert into category (id, name) values (411, 'Landscaping & Irrigation');
insert into category (id, name) values (412, 'Soft Flooring and Base');
insert into category (id, name) values (413, 'Curb & Gutter');
insert into category (id, name) values (414, 'Ornamental Railings');
insert into category (id, name) values (415, 'Soft Flooring and Base');
insert into category (id, name) values (416, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (417, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (418, 'Soft Flooring and Base');
insert into category (id, name) values (419, 'Exterior Signage');
insert into category (id, name) values (420, 'Construction Clean and Final Clean');
insert into category (id, name) values (421, 'Drilled Shafts');
insert into category (id, name) values (422, 'RF Shielding');
insert into category (id, name) values (423, 'Drilled Shafts');
insert into category (id, name) values (424, 'Elevator');
insert into category (id, name) values (425, 'Termite Control');
insert into category (id, name) values (426, 'Framing (Wood)');
insert into category (id, name) values (427, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (428, 'Elevator');
insert into category (id, name) values (429, 'HVAC');
insert into category (id, name) values (430, 'Elevator');
insert into category (id, name) values (431, 'Epoxy Flooring');
insert into category (id, name) values (432, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (433, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (434, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (435, 'Elevator');
insert into category (id, name) values (436, 'Fire Sprinkler System');
insert into category (id, name) values (437, 'Doors, Frames & Hardware');
insert into category (id, name) values (438, 'Plumbing & Medical Gas');
insert into category (id, name) values (439, 'Framing (Steel)');
insert into category (id, name) values (440, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (441, 'Granite Surfaces');
insert into category (id, name) values (442, 'RF Shielding');
insert into category (id, name) values (443, 'Roofing (Asphalt)');
insert into category (id, name) values (444, 'Curb & Gutter');
insert into category (id, name) values (445, 'Framing (Steel)');
insert into category (id, name) values (446, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (447, 'Plumbing & Medical Gas');
insert into category (id, name) values (448, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (449, 'Roofing (Asphalt)');
insert into category (id, name) values (450, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (451, 'Elevator');
insert into category (id, name) values (452, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (453, 'Landscaping & Irrigation');
insert into category (id, name) values (454, 'Casework');
insert into category (id, name) values (455, 'Epoxy Flooring');
insert into category (id, name) values (456, 'EIFS');
insert into category (id, name) values (457, 'Electrical and Fire Alarm');
insert into category (id, name) values (458, 'Framing (Steel)');
insert into category (id, name) values (459, 'Framing (Steel)');
insert into category (id, name) values (460, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (461, 'Curb & Gutter');
insert into category (id, name) values (462, 'Construction Clean and Final Clean');
insert into category (id, name) values (463, 'Wall Protection');
insert into category (id, name) values (464, 'Elevator');
insert into category (id, name) values (465, 'HVAC');
insert into category (id, name) values (466, 'Framing (Steel)');
insert into category (id, name) values (467, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (468, 'Framing (Steel)');
insert into category (id, name) values (469, 'Overhead Doors');
insert into category (id, name) values (470, 'Fire Protection');
insert into category (id, name) values (471, 'Ornamental Railings');
insert into category (id, name) values (472, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (473, 'Fire Protection');
insert into category (id, name) values (474, 'Epoxy Flooring');
insert into category (id, name) values (475, 'Ornamental Railings');
insert into category (id, name) values (476, 'Electrical and Fire Alarm');
insert into category (id, name) values (477, 'Site Furnishings');
insert into category (id, name) values (478, 'Site Furnishings');
insert into category (id, name) values (479, 'Termite Control');
insert into category (id, name) values (480, 'Waterproofing & Caulking');
insert into category (id, name) values (481, 'Construction Clean and Final Clean');
insert into category (id, name) values (482, 'Exterior Signage');
insert into category (id, name) values (483, 'EIFS');
insert into category (id, name) values (484, 'RF Shielding');
insert into category (id, name) values (485, 'Glass & Glazing');
insert into category (id, name) values (486, 'Glass & Glazing');
insert into category (id, name) values (487, 'RF Shielding');
insert into category (id, name) values (488, 'Granite Surfaces');
insert into category (id, name) values (489, 'Masonry');
insert into category (id, name) values (490, 'Electrical and Fire Alarm');
insert into category (id, name) values (491, 'Wall Protection');
insert into category (id, name) values (492, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (493, 'Exterior Signage');
insert into category (id, name) values (494, 'Framing (Wood)');
insert into category (id, name) values (495, 'Electrical and Fire Alarm');
insert into category (id, name) values (496, 'Plumbing & Medical Gas');
insert into category (id, name) values (497, 'Electrical');
insert into category (id, name) values (498, 'Electrical');
insert into category (id, name) values (499, 'HVAC');
insert into category (id, name) values (500, 'Curb & Gutter');
insert into category (id, name) values (501, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (502, 'Landscaping & Irrigation');
insert into category (id, name) values (503, 'RF Shielding');
insert into category (id, name) values (504, 'Waterproofing & Caulking');
insert into category (id, name) values (505, 'Landscaping & Irrigation');
insert into category (id, name) values (506, 'Roofing (Metal)');
insert into category (id, name) values (507, 'Structural & Misc Steel Erection');
insert into category (id, name) values (508, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (509, 'Construction Clean and Final Clean');
insert into category (id, name) values (510, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (511, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (512, 'Ornamental Railings');
insert into category (id, name) values (513, 'Doors, Frames & Hardware');
insert into category (id, name) values (514, 'Electrical and Fire Alarm');
insert into category (id, name) values (515, 'Termite Control');
insert into category (id, name) values (516, 'RF Shielding');
insert into category (id, name) values (517, 'Masonry & Precast');
insert into category (id, name) values (518, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (519, 'EIFS');
insert into category (id, name) values (520, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (521, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (522, 'Site Furnishings');
insert into category (id, name) values (523, 'Drilled Shafts');
insert into category (id, name) values (524, 'Masonry');
insert into category (id, name) values (525, 'Masonry & Precast');
insert into category (id, name) values (526, 'Roofing (Asphalt)');
insert into category (id, name) values (527, 'Soft Flooring and Base');
insert into category (id, name) values (528, 'HVAC');
insert into category (id, name) values (529, 'Soft Flooring and Base');
insert into category (id, name) values (530, 'RF Shielding');
insert into category (id, name) values (531, 'RF Shielding');
insert into category (id, name) values (532, 'Fire Protection');
insert into category (id, name) values (533, 'Wall Protection');
insert into category (id, name) values (534, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (535, 'Asphalt Paving');
insert into category (id, name) values (536, 'Masonry');
insert into category (id, name) values (537, 'Electrical');
insert into category (id, name) values (538, 'Termite Control');
insert into category (id, name) values (539, 'Roofing (Asphalt)');
insert into category (id, name) values (540, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (541, 'Casework');
insert into category (id, name) values (542, 'Glass & Glazing');
insert into category (id, name) values (543, 'Granite Surfaces');
insert into category (id, name) values (544, 'Termite Control');
insert into category (id, name) values (545, 'Hard Tile & Stone');
insert into category (id, name) values (546, 'Plumbing & Medical Gas');
insert into category (id, name) values (547, 'Roofing (Asphalt)');
insert into category (id, name) values (548, 'Termite Control');
insert into category (id, name) values (549, 'Granite Surfaces');
insert into category (id, name) values (550, 'Ornamental Railings');
insert into category (id, name) values (551, 'Waterproofing & Caulking');
insert into category (id, name) values (552, 'Plumbing & Medical Gas');
insert into category (id, name) values (553, 'Framing (Wood)');
insert into category (id, name) values (554, 'Site Furnishings');
insert into category (id, name) values (555, 'Roofing (Asphalt)');
insert into category (id, name) values (556, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (557, 'Site Furnishings');
insert into category (id, name) values (558, 'RF Shielding');
insert into category (id, name) values (559, 'Fire Sprinkler System');
insert into category (id, name) values (560, 'Masonry');
insert into category (id, name) values (561, 'Electrical');
insert into category (id, name) values (562, 'HVAC');
insert into category (id, name) values (563, 'Roofing (Asphalt)');
insert into category (id, name) values (564, 'Curb & Gutter');
insert into category (id, name) values (565, 'Doors, Frames & Hardware');
insert into category (id, name) values (566, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (567, 'Elevator');
insert into category (id, name) values (568, 'Exterior Signage');
insert into category (id, name) values (569, 'Masonry');
insert into category (id, name) values (570, 'Ornamental Railings');
insert into category (id, name) values (571, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (572, 'Site Furnishings');
insert into category (id, name) values (573, 'Sitework & Site Utilities');
insert into category (id, name) values (574, 'Waterproofing & Caulking');
insert into category (id, name) values (575, 'Structural & Misc Steel Erection');
insert into category (id, name) values (576, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (577, 'Epoxy Flooring');
insert into category (id, name) values (578, 'Waterproofing & Caulking');
insert into category (id, name) values (579, 'Framing (Steel)');
insert into category (id, name) values (580, 'Framing (Wood)');
insert into category (id, name) values (581, 'EIFS');
insert into category (id, name) values (582, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (583, 'Termite Control');
insert into category (id, name) values (584, 'Asphalt Paving');
insert into category (id, name) values (585, 'Fire Protection');
insert into category (id, name) values (586, 'Plumbing & Medical Gas');
insert into category (id, name) values (587, 'Hard Tile & Stone');
insert into category (id, name) values (588, 'Landscaping & Irrigation');
insert into category (id, name) values (589, 'Site Furnishings');
insert into category (id, name) values (590, 'Doors, Frames & Hardware');
insert into category (id, name) values (591, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (592, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (593, 'Structural & Misc Steel Erection');
insert into category (id, name) values (594, 'Termite Control');
insert into category (id, name) values (595, 'Masonry & Precast');
insert into category (id, name) values (596, 'Electrical');
insert into category (id, name) values (597, 'Landscaping & Irrigation');
insert into category (id, name) values (598, 'Ornamental Railings');
insert into category (id, name) values (599, 'Hard Tile & Stone');
insert into category (id, name) values (600, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (601, 'Waterproofing & Caulking');
insert into category (id, name) values (602, 'Electrical');
insert into category (id, name) values (603, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (604, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (605, 'Plumbing & Medical Gas');
insert into category (id, name) values (606, 'Glass & Glazing');
insert into category (id, name) values (607, 'Masonry & Precast');
insert into category (id, name) values (608, 'Sitework & Site Utilities');
insert into category (id, name) values (609, 'Fire Protection');
insert into category (id, name) values (610, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (611, 'Roofing (Asphalt)');
insert into category (id, name) values (612, 'Framing (Wood)');
insert into category (id, name) values (613, 'Sitework & Site Utilities');
insert into category (id, name) values (614, 'Sitework & Site Utilities');
insert into category (id, name) values (615, 'Termite Control');
insert into category (id, name) values (616, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (617, 'Ornamental Railings');
insert into category (id, name) values (618, 'Masonry & Precast');
insert into category (id, name) values (619, 'Hard Tile & Stone');
insert into category (id, name) values (620, 'Doors, Frames & Hardware');
insert into category (id, name) values (621, 'Overhead Doors');
insert into category (id, name) values (622, 'Landscaping & Irrigation');
insert into category (id, name) values (623, 'Casework');
insert into category (id, name) values (624, 'Landscaping & Irrigation');
insert into category (id, name) values (625, 'Exterior Signage');
insert into category (id, name) values (626, 'Wall Protection');
insert into category (id, name) values (627, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (628, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (629, 'Roofing (Metal)');
insert into category (id, name) values (630, 'Glass & Glazing');
insert into category (id, name) values (631, 'Soft Flooring and Base');
insert into category (id, name) values (632, 'Hard Tile & Stone');
insert into category (id, name) values (633, 'Framing (Steel)');
insert into category (id, name) values (634, 'Waterproofing & Caulking');
insert into category (id, name) values (635, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (636, 'Asphalt Paving');
insert into category (id, name) values (637, 'Glass & Glazing');
insert into category (id, name) values (638, 'Doors, Frames & Hardware');
insert into category (id, name) values (639, 'Exterior Signage');
insert into category (id, name) values (640, 'Drilled Shafts');
insert into category (id, name) values (641, 'Casework');
insert into category (id, name) values (642, 'Exterior Signage');
insert into category (id, name) values (643, 'Asphalt Paving');
insert into category (id, name) values (644, 'Fire Protection');
insert into category (id, name) values (645, 'Asphalt Paving');
insert into category (id, name) values (646, 'Soft Flooring and Base');
insert into category (id, name) values (647, 'Glass & Glazing');
insert into category (id, name) values (648, 'Casework');
insert into category (id, name) values (649, 'Masonry & Precast');
insert into category (id, name) values (650, 'Overhead Doors');
insert into category (id, name) values (651, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (652, 'Plumbing & Medical Gas');
insert into category (id, name) values (653, 'Framing (Wood)');
insert into category (id, name) values (654, 'Exterior Signage');
insert into category (id, name) values (655, 'Roofing (Metal)');
insert into category (id, name) values (656, 'Masonry');
insert into category (id, name) values (657, 'Fire Sprinkler System');
insert into category (id, name) values (658, 'Waterproofing & Caulking');
insert into category (id, name) values (659, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (660, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (661, 'Plumbing & Medical Gas');
insert into category (id, name) values (662, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (663, 'Sitework & Site Utilities');
insert into category (id, name) values (664, 'Casework');
insert into category (id, name) values (665, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (666, 'Wall Protection');
insert into category (id, name) values (667, 'Sitework & Site Utilities');
insert into category (id, name) values (668, 'Glass & Glazing');
insert into category (id, name) values (669, 'Framing (Wood)');
insert into category (id, name) values (670, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (671, 'Granite Surfaces');
insert into category (id, name) values (672, 'RF Shielding');
insert into category (id, name) values (673, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (674, 'Framing (Steel)');
insert into category (id, name) values (675, 'Structural & Misc Steel Erection');
insert into category (id, name) values (676, 'EIFS');
insert into category (id, name) values (677, 'Curb & Gutter');
insert into category (id, name) values (678, 'Roofing (Metal)');
insert into category (id, name) values (679, 'Roofing (Asphalt)');
insert into category (id, name) values (680, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (681, 'Fire Protection');
insert into category (id, name) values (682, 'Construction Clean and Final Clean');
insert into category (id, name) values (683, 'Ornamental Railings');
insert into category (id, name) values (684, 'Soft Flooring and Base');
insert into category (id, name) values (685, 'Marlite Panels (FED)');
insert into category (id, name) values (686, 'Framing (Steel)');
insert into category (id, name) values (687, 'Marlite Panels (FED)');
insert into category (id, name) values (688, 'Glass & Glazing');
insert into category (id, name) values (689, 'Wall Protection');
insert into category (id, name) values (690, 'HVAC');
insert into category (id, name) values (691, 'Fire Protection');
insert into category (id, name) values (692, 'Roofing (Asphalt)');
insert into category (id, name) values (693, 'Fire Sprinkler System');
insert into category (id, name) values (694, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (695, 'Landscaping & Irrigation');
insert into category (id, name) values (696, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (697, 'Casework');
insert into category (id, name) values (698, 'EIFS');
insert into category (id, name) values (699, 'Electrical');
insert into category (id, name) values (700, 'RF Shielding');
insert into category (id, name) values (701, 'Masonry');
insert into category (id, name) values (702, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (703, 'Framing (Steel)');
insert into category (id, name) values (704, 'Soft Flooring and Base');
insert into category (id, name) values (705, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (706, 'Termite Control');
insert into category (id, name) values (707, 'Elevator');
insert into category (id, name) values (708, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (709, 'Casework');
insert into category (id, name) values (710, 'Sitework & Site Utilities');
insert into category (id, name) values (711, 'Ornamental Railings');
insert into category (id, name) values (712, 'Framing (Steel)');
insert into category (id, name) values (713, 'Site Furnishings');
insert into category (id, name) values (714, 'Sitework & Site Utilities');
insert into category (id, name) values (715, 'Asphalt Paving');
insert into category (id, name) values (716, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (717, 'Exterior Signage');
insert into category (id, name) values (718, 'Sitework & Site Utilities');
insert into category (id, name) values (719, 'Asphalt Paving');
insert into category (id, name) values (720, 'Asphalt Paving');
insert into category (id, name) values (721, 'Glass & Glazing');
insert into category (id, name) values (722, 'Masonry & Precast');
insert into category (id, name) values (723, 'Epoxy Flooring');
insert into category (id, name) values (724, 'Drilled Shafts');
insert into category (id, name) values (725, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (726, 'Casework');
insert into category (id, name) values (727, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (728, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (729, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (730, 'HVAC');
insert into category (id, name) values (731, 'Soft Flooring and Base');
insert into category (id, name) values (732, 'Electrical and Fire Alarm');
insert into category (id, name) values (733, 'Roofing (Metal)');
insert into category (id, name) values (734, 'Soft Flooring and Base');
insert into category (id, name) values (735, 'HVAC');
insert into category (id, name) values (736, 'Sitework & Site Utilities');
insert into category (id, name) values (737, 'Masonry');
insert into category (id, name) values (738, 'Framing (Wood)');
insert into category (id, name) values (739, 'Roofing (Asphalt)');
insert into category (id, name) values (740, 'Fire Protection');
insert into category (id, name) values (741, 'Marlite Panels (FED)');
insert into category (id, name) values (742, 'Overhead Doors');
insert into category (id, name) values (743, 'Epoxy Flooring');
insert into category (id, name) values (744, 'Curb & Gutter');
insert into category (id, name) values (745, 'Asphalt Paving');
insert into category (id, name) values (746, 'Framing (Wood)');
insert into category (id, name) values (747, 'Curb & Gutter');
insert into category (id, name) values (748, 'Granite Surfaces');
insert into category (id, name) values (749, 'Soft Flooring and Base');
insert into category (id, name) values (750, 'Fire Sprinkler System');
insert into category (id, name) values (751, 'Soft Flooring and Base');
insert into category (id, name) values (752, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (753, 'Site Furnishings');
insert into category (id, name) values (754, 'Epoxy Flooring');
insert into category (id, name) values (755, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (756, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (757, 'Drilled Shafts');
insert into category (id, name) values (758, 'Curb & Gutter');
insert into category (id, name) values (759, 'Electrical and Fire Alarm');
insert into category (id, name) values (760, 'Masonry');
insert into category (id, name) values (761, 'Overhead Doors');
insert into category (id, name) values (762, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (763, 'Asphalt Paving');
insert into category (id, name) values (764, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (765, 'Construction Clean and Final Clean');
insert into category (id, name) values (766, 'Construction Clean and Final Clean');
insert into category (id, name) values (767, 'Roofing (Asphalt)');
insert into category (id, name) values (768, 'Drilled Shafts');
insert into category (id, name) values (769, 'Marlite Panels (FED)');
insert into category (id, name) values (770, 'Roofing (Asphalt)');
insert into category (id, name) values (771, 'Waterproofing & Caulking');
insert into category (id, name) values (772, 'Masonry & Precast');
insert into category (id, name) values (773, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (774, 'Electrical');
insert into category (id, name) values (775, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (776, 'Fire Sprinkler System');
insert into category (id, name) values (777, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (778, 'Epoxy Flooring');
insert into category (id, name) values (779, 'Fire Sprinkler System');
insert into category (id, name) values (780, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (781, 'Site Furnishings');
insert into category (id, name) values (782, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (783, 'Landscaping & Irrigation');
insert into category (id, name) values (784, 'RF Shielding');
insert into category (id, name) values (785, 'Elevator');
insert into category (id, name) values (786, 'Elevator');
insert into category (id, name) values (787, 'Masonry');
insert into category (id, name) values (788, 'Epoxy Flooring');
insert into category (id, name) values (789, 'Hard Tile & Stone');
insert into category (id, name) values (790, 'Plumbing & Medical Gas');
insert into category (id, name) values (791, 'Construction Clean and Final Clean');
insert into category (id, name) values (792, 'Doors, Frames & Hardware');
insert into category (id, name) values (793, 'Granite Surfaces');
insert into category (id, name) values (794, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (795, 'Fire Sprinkler System');
insert into category (id, name) values (796, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (797, 'Masonry & Precast');
insert into category (id, name) values (798, 'RF Shielding');
insert into category (id, name) values (799, 'Fire Protection');
insert into category (id, name) values (800, 'Wall Protection');
insert into category (id, name) values (801, 'HVAC');
insert into category (id, name) values (802, 'Roofing (Asphalt)');
insert into category (id, name) values (803, 'Framing (Wood)');
insert into category (id, name) values (804, 'RF Shielding');
insert into category (id, name) values (805, 'Masonry');
insert into category (id, name) values (806, 'Fire Protection');
insert into category (id, name) values (807, 'Construction Clean and Final Clean');
insert into category (id, name) values (808, 'Waterproofing & Caulking');
insert into category (id, name) values (809, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (810, 'Landscaping & Irrigation');
insert into category (id, name) values (811, 'EIFS');
insert into category (id, name) values (812, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (813, 'Framing (Steel)');
insert into category (id, name) values (814, 'Masonry & Precast');
insert into category (id, name) values (815, 'Glass & Glazing');
insert into category (id, name) values (816, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (817, 'EIFS');
insert into category (id, name) values (818, 'Electrical');
insert into category (id, name) values (819, 'Construction Clean and Final Clean');
insert into category (id, name) values (820, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (821, 'Structural & Misc Steel Erection');
insert into category (id, name) values (822, 'Wall Protection');
insert into category (id, name) values (823, 'RF Shielding');
insert into category (id, name) values (824, 'Masonry & Precast');
insert into category (id, name) values (825, 'Overhead Doors');
insert into category (id, name) values (826, 'Termite Control');
insert into category (id, name) values (827, 'Wall Protection');
insert into category (id, name) values (828, 'Doors, Frames & Hardware');
insert into category (id, name) values (829, 'Marlite Panels (FED)');
insert into category (id, name) values (830, 'Structural & Misc Steel Erection');
insert into category (id, name) values (831, 'Termite Control');
insert into category (id, name) values (832, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (833, 'Structural & Misc Steel Erection');
insert into category (id, name) values (834, 'EIFS');
insert into category (id, name) values (835, 'Electrical and Fire Alarm');
insert into category (id, name) values (836, 'Termite Control');
insert into category (id, name) values (837, 'Structural & Misc Steel Erection');
insert into category (id, name) values (838, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (839, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (840, 'Drilled Shafts');
insert into category (id, name) values (841, 'Electrical and Fire Alarm');
insert into category (id, name) values (842, 'Framing (Wood)');
insert into category (id, name) values (843, 'Doors, Frames & Hardware');
insert into category (id, name) values (844, 'Wall Protection');
insert into category (id, name) values (845, 'Masonry');
insert into category (id, name) values (846, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (847, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (848, 'Roofing (Metal)');
insert into category (id, name) values (849, 'Roofing (Metal)');
insert into category (id, name) values (850, 'Exterior Signage');
insert into category (id, name) values (851, 'Casework');
insert into category (id, name) values (852, 'Sitework & Site Utilities');
insert into category (id, name) values (853, 'Termite Control');
insert into category (id, name) values (854, 'RF Shielding');
insert into category (id, name) values (855, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (856, 'Asphalt Paving');
insert into category (id, name) values (857, 'Glass & Glazing');
insert into category (id, name) values (858, 'Roofing (Metal)');
insert into category (id, name) values (859, 'Landscaping & Irrigation');
insert into category (id, name) values (860, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (861, 'Ornamental Railings');
insert into category (id, name) values (862, 'HVAC');
insert into category (id, name) values (863, 'RF Shielding');
insert into category (id, name) values (864, 'Fire Sprinkler System');
insert into category (id, name) values (865, 'Epoxy Flooring');
insert into category (id, name) values (866, 'Elevator');
insert into category (id, name) values (867, 'Framing (Steel)');
insert into category (id, name) values (868, 'RF Shielding');
insert into category (id, name) values (869, 'Structural & Misc Steel Erection');
insert into category (id, name) values (870, 'Exterior Signage');
insert into category (id, name) values (871, 'Plumbing & Medical Gas');
insert into category (id, name) values (872, 'Asphalt Paving');
insert into category (id, name) values (873, 'Electrical and Fire Alarm');
insert into category (id, name) values (874, 'Landscaping & Irrigation');
insert into category (id, name) values (875, 'Asphalt Paving');
insert into category (id, name) values (876, 'Roofing (Metal)');
insert into category (id, name) values (877, 'Soft Flooring and Base');
insert into category (id, name) values (878, 'Granite Surfaces');
insert into category (id, name) values (879, 'Fire Protection');
insert into category (id, name) values (880, 'Structural & Misc Steel Erection');
insert into category (id, name) values (881, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (882, 'Curb & Gutter');
insert into category (id, name) values (883, 'EIFS');
insert into category (id, name) values (884, 'Exterior Signage');
insert into category (id, name) values (885, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (886, 'Exterior Signage');
insert into category (id, name) values (887, 'Ornamental Railings');
insert into category (id, name) values (888, 'Exterior Signage');
insert into category (id, name) values (889, 'Overhead Doors');
insert into category (id, name) values (890, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (891, 'Masonry');
insert into category (id, name) values (892, 'Waterproofing & Caulking');
insert into category (id, name) values (893, 'Framing (Wood)');
insert into category (id, name) values (894, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (895, 'Hard Tile & Stone');
insert into category (id, name) values (896, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (897, 'Drilled Shafts');
insert into category (id, name) values (898, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (899, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (900, 'Construction Clean and Final Clean');
insert into category (id, name) values (901, 'Doors, Frames & Hardware');
insert into category (id, name) values (902, 'Elevator');
insert into category (id, name) values (903, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (904, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (905, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (906, 'Sitework & Site Utilities');
insert into category (id, name) values (907, 'Sitework & Site Utilities');
insert into category (id, name) values (908, 'Ornamental Railings');
insert into category (id, name) values (909, 'Masonry & Precast');
insert into category (id, name) values (910, 'Waterproofing & Caulking');
insert into category (id, name) values (911, 'Roofing (Asphalt)');
insert into category (id, name) values (912, 'Fire Sprinkler System');
insert into category (id, name) values (913, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (914, 'Wall Protection');
insert into category (id, name) values (915, 'RF Shielding');
insert into category (id, name) values (916, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (917, 'Fire Sprinkler System');
insert into category (id, name) values (918, 'Landscaping & Irrigation');
insert into category (id, name) values (919, 'Electrical and Fire Alarm');
insert into category (id, name) values (920, 'Framing (Steel)');
insert into category (id, name) values (921, 'Hard Tile & Stone');
insert into category (id, name) values (922, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (923, 'Overhead Doors');
insert into category (id, name) values (924, 'Waterproofing & Caulking');
insert into category (id, name) values (925, 'Waterproofing & Caulking');
insert into category (id, name) values (926, 'Elevator');
insert into category (id, name) values (927, 'Electrical');
insert into category (id, name) values (928, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (929, 'Masonry');
insert into category (id, name) values (930, 'Framing (Steel)');
insert into category (id, name) values (931, 'Granite Surfaces');
insert into category (id, name) values (932, 'Asphalt Paving');
insert into category (id, name) values (933, 'Construction Clean and Final Clean');
insert into category (id, name) values (934, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (935, 'HVAC');
insert into category (id, name) values (936, 'Marlite Panels (FED)');
insert into category (id, name) values (937, 'Masonry & Precast');
insert into category (id, name) values (938, 'Fire Protection');
insert into category (id, name) values (939, 'Ornamental Railings');
insert into category (id, name) values (940, 'Masonry');
insert into category (id, name) values (941, 'Elevator');
insert into category (id, name) values (942, 'Electrical and Fire Alarm');
insert into category (id, name) values (943, 'Drilled Shafts');
insert into category (id, name) values (944, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (945, 'Termite Control');
insert into category (id, name) values (946, 'Landscaping & Irrigation');
insert into category (id, name) values (947, 'Roofing (Metal)');
insert into category (id, name) values (948, 'Termite Control');
insert into category (id, name) values (949, 'Curb & Gutter');
insert into category (id, name) values (950, 'Wall Protection');
insert into category (id, name) values (951, 'RF Shielding');
insert into category (id, name) values (952, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (953, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (954, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (955, 'RF Shielding');
insert into category (id, name) values (956, 'Doors, Frames & Hardware');
insert into category (id, name) values (957, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (958, 'Hard Tile & Stone');
insert into category (id, name) values (959, 'Wall Protection');
insert into category (id, name) values (960, 'Framing (Steel)');
insert into category (id, name) values (961, 'Doors, Frames & Hardware');
insert into category (id, name) values (962, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (963, 'EIFS');
insert into category (id, name) values (964, 'Electrical');
insert into category (id, name) values (965, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (966, 'Framing (Wood)');
insert into category (id, name) values (967, 'Fire Sprinkler System');
insert into category (id, name) values (968, 'Roofing (Metal)');
insert into category (id, name) values (969, 'Doors, Frames & Hardware');
insert into category (id, name) values (970, 'Structural & Misc Steel Erection');
insert into category (id, name) values (971, 'Termite Control');
insert into category (id, name) values (972, 'Wall Protection');
insert into category (id, name) values (973, 'Fire Sprinkler System');
insert into category (id, name) values (974, 'Asphalt Paving');
insert into category (id, name) values (975, 'Soft Flooring and Base');
insert into category (id, name) values (976, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (977, 'Site Furnishings');
insert into category (id, name) values (978, 'Site Furnishings');
insert into category (id, name) values (979, 'Construction Clean and Final Clean');
insert into category (id, name) values (980, 'Marlite Panels (FED)');
insert into category (id, name) values (981, 'Drilled Shafts');
insert into category (id, name) values (982, 'Framing (Steel)');
insert into category (id, name) values (983, 'Elevator');
insert into category (id, name) values (984, 'Site Furnishings');
insert into category (id, name) values (985, 'Drilled Shafts');
insert into category (id, name) values (986, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (987, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (988, 'Overhead Doors');
insert into category (id, name) values (989, 'Termite Control');
insert into category (id, name) values (990, 'Masonry & Precast');
insert into category (id, name) values (991, 'Drilled Shafts');
insert into category (id, name) values (992, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (993, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (994, 'Elevator');
insert into category (id, name) values (995, 'Fire Sprinkler System');
insert into category (id, name) values (996, 'Soft Flooring and Base');
insert into category (id, name) values (997, 'Drilled Shafts');
insert into category (id, name) values (998, 'EIFS');
insert into category (id, name) values (999, 'Landscaping & Irrigation');
insert into category (id, name) values (1000, 'Exterior Signage');
