create table category (
	id INT,
	name VARCHAR(50)
);
insert into category (id, name) values (1, 'Landscaping & Irrigation');
insert into category (id, name) values (2, 'Fire Sprinkler System');
insert into category (id, name) values (3, 'Termite Control');
insert into category (id, name) values (4, 'Sitework & Site Utilities');
insert into category (id, name) values (5, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (6, 'Waterproofing & Caulking');
insert into category (id, name) values (7, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (8, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (9, 'Casework');
insert into category (id, name) values (10, 'Fire Sprinkler System');
insert into category (id, name) values (11, 'Construction Clean and Final Clean');
insert into category (id, name) values (12, 'EIFS');
insert into category (id, name) values (13, 'RF Shielding');
insert into category (id, name) values (14, 'Epoxy Flooring');
insert into category (id, name) values (15, 'Electrical');
insert into category (id, name) values (16, 'Sitework & Site Utilities');
insert into category (id, name) values (17, 'Plumbing & Medical Gas');
insert into category (id, name) values (18, 'HVAC');
insert into category (id, name) values (19, 'Hard Tile & Stone');
insert into category (id, name) values (20, 'Exterior Signage');
insert into category (id, name) values (21, 'Construction Clean and Final Clean');
insert into category (id, name) values (22, 'Site Furnishings');
insert into category (id, name) values (23, 'Wall Protection');
insert into category (id, name) values (24, 'Fire Sprinkler System');
insert into category (id, name) values (25, 'EIFS');
insert into category (id, name) values (26, 'Glass & Glazing');
insert into category (id, name) values (27, 'Ornamental Railings');
insert into category (id, name) values (28, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (29, 'Fire Sprinkler System');
insert into category (id, name) values (30, 'Exterior Signage');
insert into category (id, name) values (31, 'Epoxy Flooring');
insert into category (id, name) values (32, 'Framing (Wood)');
insert into category (id, name) values (33, 'Glass & Glazing');
insert into category (id, name) values (34, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (35, 'Casework');
insert into category (id, name) values (36, 'Sitework & Site Utilities');
insert into category (id, name) values (37, 'Roofing (Metal)');
insert into category (id, name) values (38, 'Drilled Shafts');
insert into category (id, name) values (39, 'Ornamental Railings');
insert into category (id, name) values (40, 'Electrical');
insert into category (id, name) values (41, 'RF Shielding');
insert into category (id, name) values (42, 'Electrical');
insert into category (id, name) values (43, 'Granite Surfaces');
insert into category (id, name) values (44, 'Glass & Glazing');
insert into category (id, name) values (45, 'Doors, Frames & Hardware');
insert into category (id, name) values (46, 'Landscaping & Irrigation');
insert into category (id, name) values (47, 'Roofing (Metal)');
insert into category (id, name) values (48, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (49, 'Fire Sprinkler System');
insert into category (id, name) values (50, 'Doors, Frames & Hardware');
insert into category (id, name) values (51, 'Soft Flooring and Base');
insert into category (id, name) values (52, 'Termite Control');
insert into category (id, name) values (53, 'Granite Surfaces');
insert into category (id, name) values (54, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (55, 'Epoxy Flooring');
insert into category (id, name) values (56, 'Waterproofing & Caulking');
insert into category (id, name) values (57, 'Structural & Misc Steel Erection');
insert into category (id, name) values (58, 'Fire Protection');
insert into category (id, name) values (59, 'Overhead Doors');
insert into category (id, name) values (60, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (61, 'Elevator');
insert into category (id, name) values (62, 'Doors, Frames & Hardware');
insert into category (id, name) values (63, 'Termite Control');
insert into category (id, name) values (64, 'Termite Control');
insert into category (id, name) values (65, 'Structural & Misc Steel Erection');
insert into category (id, name) values (66, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (67, 'Wall Protection');
insert into category (id, name) values (68, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (69, 'Roofing (Metal)');
insert into category (id, name) values (70, 'HVAC');
insert into category (id, name) values (71, 'Sitework & Site Utilities');
insert into category (id, name) values (72, 'Doors, Frames & Hardware');
insert into category (id, name) values (73, 'Termite Control');
insert into category (id, name) values (74, 'Plumbing & Medical Gas');
insert into category (id, name) values (75, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (76, 'Plumbing & Medical Gas');
insert into category (id, name) values (77, 'Asphalt Paving');
insert into category (id, name) values (78, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (79, 'Ornamental Railings');
insert into category (id, name) values (80, 'Fire Sprinkler System');
insert into category (id, name) values (81, 'Landscaping & Irrigation');
insert into category (id, name) values (82, 'Structural & Misc Steel Erection');
insert into category (id, name) values (83, 'Exterior Signage');
insert into category (id, name) values (84, 'Wall Protection');
insert into category (id, name) values (85, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (86, 'Framing (Steel)');
insert into category (id, name) values (87, 'Epoxy Flooring');
insert into category (id, name) values (88, 'Framing (Steel)');
insert into category (id, name) values (89, 'Roofing (Asphalt)');
insert into category (id, name) values (90, 'Construction Clean and Final Clean');
insert into category (id, name) values (91, 'Doors, Frames & Hardware');
insert into category (id, name) values (92, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (93, 'Marlite Panels (FED)');
insert into category (id, name) values (94, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (95, 'Asphalt Paving');
insert into category (id, name) values (96, 'Plumbing & Medical Gas');
insert into category (id, name) values (97, 'RF Shielding');
insert into category (id, name) values (98, 'Wall Protection');
insert into category (id, name) values (99, 'Drilled Shafts');
insert into category (id, name) values (100, 'Waterproofing & Caulking');
insert into category (id, name) values (101, 'Fire Protection');
insert into category (id, name) values (102, 'Construction Clean and Final Clean');
insert into category (id, name) values (103, 'HVAC');
insert into category (id, name) values (104, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (105, 'Structural & Misc Steel Erection');
insert into category (id, name) values (106, 'Casework');
insert into category (id, name) values (107, 'Roofing (Asphalt)');
insert into category (id, name) values (108, 'Plumbing & Medical Gas');
insert into category (id, name) values (109, 'Structural & Misc Steel Erection');
insert into category (id, name) values (110, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (111, 'Construction Clean and Final Clean');
insert into category (id, name) values (112, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (113, 'Epoxy Flooring');
insert into category (id, name) values (114, 'Framing (Wood)');
insert into category (id, name) values (115, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (116, 'Framing (Steel)');
insert into category (id, name) values (117, 'Roofing (Metal)');
insert into category (id, name) values (118, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (119, 'Waterproofing & Caulking');
insert into category (id, name) values (120, 'Landscaping & Irrigation');
insert into category (id, name) values (121, 'Curb & Gutter');
insert into category (id, name) values (122, 'Roofing (Metal)');
insert into category (id, name) values (123, 'Soft Flooring and Base');
insert into category (id, name) values (124, 'Curb & Gutter');
insert into category (id, name) values (125, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (126, 'Fire Protection');
insert into category (id, name) values (127, 'Curb & Gutter');
insert into category (id, name) values (128, 'Masonry & Precast');
insert into category (id, name) values (129, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (130, 'Glass & Glazing');
insert into category (id, name) values (131, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (132, 'Electrical');
insert into category (id, name) values (133, 'Waterproofing & Caulking');
insert into category (id, name) values (134, 'Marlite Panels (FED)');
insert into category (id, name) values (135, 'Electrical');
insert into category (id, name) values (136, 'Hard Tile & Stone');
insert into category (id, name) values (137, 'Fire Protection');
insert into category (id, name) values (138, 'Soft Flooring and Base');
insert into category (id, name) values (139, 'Landscaping & Irrigation');
insert into category (id, name) values (140, 'Electrical and Fire Alarm');
insert into category (id, name) values (141, 'Site Furnishings');
insert into category (id, name) values (142, 'EIFS');
insert into category (id, name) values (143, 'Elevator');
insert into category (id, name) values (144, 'EIFS');
insert into category (id, name) values (145, 'HVAC');
insert into category (id, name) values (146, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (147, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (148, 'Waterproofing & Caulking');
insert into category (id, name) values (149, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (150, 'Sitework & Site Utilities');
insert into category (id, name) values (151, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (152, 'Masonry');
insert into category (id, name) values (153, 'Asphalt Paving');
insert into category (id, name) values (154, 'Sitework & Site Utilities');
insert into category (id, name) values (155, 'Construction Clean and Final Clean');
insert into category (id, name) values (156, 'Glass & Glazing');
insert into category (id, name) values (157, 'Roofing (Metal)');
insert into category (id, name) values (158, 'Structural & Misc Steel Erection');
insert into category (id, name) values (159, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (160, 'Plumbing & Medical Gas');
insert into category (id, name) values (161, 'Landscaping & Irrigation');
insert into category (id, name) values (162, 'Casework');
insert into category (id, name) values (163, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (164, 'RF Shielding');
insert into category (id, name) values (165, 'Epoxy Flooring');
insert into category (id, name) values (166, 'Sitework & Site Utilities');
insert into category (id, name) values (167, 'Marlite Panels (FED)');
insert into category (id, name) values (168, 'Fire Protection');
insert into category (id, name) values (169, 'Waterproofing & Caulking');
insert into category (id, name) values (170, 'Structural & Misc Steel Erection');
insert into category (id, name) values (171, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (172, 'Framing (Wood)');
insert into category (id, name) values (173, 'Framing (Steel)');
insert into category (id, name) values (174, 'Drilled Shafts');
insert into category (id, name) values (175, 'Ornamental Railings');
insert into category (id, name) values (176, 'Asphalt Paving');
insert into category (id, name) values (177, 'RF Shielding');
insert into category (id, name) values (178, 'Roofing (Metal)');
insert into category (id, name) values (179, 'Masonry');
insert into category (id, name) values (180, 'Waterproofing & Caulking');
insert into category (id, name) values (181, 'Plumbing & Medical Gas');
insert into category (id, name) values (182, 'Curb & Gutter');
insert into category (id, name) values (183, 'Exterior Signage');
insert into category (id, name) values (184, 'Soft Flooring and Base');
insert into category (id, name) values (185, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (186, 'Site Furnishings');
insert into category (id, name) values (187, 'Overhead Doors');
insert into category (id, name) values (188, 'Structural & Misc Steel Erection');
insert into category (id, name) values (189, 'Hard Tile & Stone');
insert into category (id, name) values (190, 'Wall Protection');
insert into category (id, name) values (191, 'Hard Tile & Stone');
insert into category (id, name) values (192, 'Curb & Gutter');
insert into category (id, name) values (193, 'Soft Flooring and Base');
insert into category (id, name) values (194, 'Site Furnishings');
insert into category (id, name) values (195, 'Granite Surfaces');
insert into category (id, name) values (196, 'Drilled Shafts');
insert into category (id, name) values (197, 'Fire Sprinkler System');
insert into category (id, name) values (198, 'Marlite Panels (FED)');
insert into category (id, name) values (199, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (200, 'Epoxy Flooring');
insert into category (id, name) values (201, 'Fire Protection');
insert into category (id, name) values (202, 'Construction Clean and Final Clean');
insert into category (id, name) values (203, 'RF Shielding');
insert into category (id, name) values (204, 'Granite Surfaces');
insert into category (id, name) values (205, 'Framing (Wood)');
insert into category (id, name) values (206, 'Site Furnishings');
insert into category (id, name) values (207, 'EIFS');
insert into category (id, name) values (208, 'Masonry');
insert into category (id, name) values (209, 'Wall Protection');
insert into category (id, name) values (210, 'Ornamental Railings');
insert into category (id, name) values (211, 'Framing (Steel)');
insert into category (id, name) values (212, 'Drilled Shafts');
insert into category (id, name) values (213, 'Doors, Frames & Hardware');
insert into category (id, name) values (214, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (215, 'Overhead Doors');
insert into category (id, name) values (216, 'Soft Flooring and Base');
insert into category (id, name) values (217, 'Roofing (Asphalt)');
insert into category (id, name) values (218, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (219, 'Elevator');
insert into category (id, name) values (220, 'Framing (Steel)');
insert into category (id, name) values (221, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (222, 'Sitework & Site Utilities');
insert into category (id, name) values (223, 'Granite Surfaces');
insert into category (id, name) values (224, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (225, 'Overhead Doors');
insert into category (id, name) values (226, 'Casework');
insert into category (id, name) values (227, 'Termite Control');
insert into category (id, name) values (228, 'Electrical');
insert into category (id, name) values (229, 'HVAC');
insert into category (id, name) values (230, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (231, 'Doors, Frames & Hardware');
insert into category (id, name) values (232, 'EIFS');
insert into category (id, name) values (233, 'Marlite Panels (FED)');
insert into category (id, name) values (234, 'Termite Control');
insert into category (id, name) values (235, 'RF Shielding');
insert into category (id, name) values (236, 'Casework');
insert into category (id, name) values (237, 'Marlite Panels (FED)');
insert into category (id, name) values (238, 'Epoxy Flooring');
insert into category (id, name) values (239, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (240, 'Asphalt Paving');
insert into category (id, name) values (241, 'Sitework & Site Utilities');
insert into category (id, name) values (242, 'Waterproofing & Caulking');
insert into category (id, name) values (243, 'Roofing (Asphalt)');
insert into category (id, name) values (244, 'Elevator');
insert into category (id, name) values (245, 'HVAC');
insert into category (id, name) values (246, 'Masonry & Precast');
insert into category (id, name) values (247, 'Landscaping & Irrigation');
insert into category (id, name) values (248, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (249, 'Framing (Wood)');
insert into category (id, name) values (250, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (251, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (252, 'Soft Flooring and Base');
insert into category (id, name) values (253, 'Doors, Frames & Hardware');
insert into category (id, name) values (254, 'Roofing (Asphalt)');
insert into category (id, name) values (255, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (256, 'Waterproofing & Caulking');
insert into category (id, name) values (257, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (258, 'Epoxy Flooring');
insert into category (id, name) values (259, 'Asphalt Paving');
insert into category (id, name) values (260, 'Drilled Shafts');
insert into category (id, name) values (261, 'Framing (Steel)');
insert into category (id, name) values (262, 'Doors, Frames & Hardware');
insert into category (id, name) values (263, 'Framing (Wood)');
insert into category (id, name) values (264, 'Drilled Shafts');
insert into category (id, name) values (265, 'Ornamental Railings');
insert into category (id, name) values (266, 'Casework');
insert into category (id, name) values (267, 'Roofing (Asphalt)');
insert into category (id, name) values (268, 'Asphalt Paving');
insert into category (id, name) values (269, 'Waterproofing & Caulking');
insert into category (id, name) values (270, 'Exterior Signage');
insert into category (id, name) values (271, 'Framing (Wood)');
insert into category (id, name) values (272, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (273, 'Electrical and Fire Alarm');
insert into category (id, name) values (274, 'Fire Sprinkler System');
insert into category (id, name) values (275, 'Overhead Doors');
insert into category (id, name) values (276, 'Structural & Misc Steel Erection');
insert into category (id, name) values (277, 'Ornamental Railings');
insert into category (id, name) values (278, 'HVAC');
insert into category (id, name) values (279, 'Landscaping & Irrigation');
insert into category (id, name) values (280, 'Hard Tile & Stone');
insert into category (id, name) values (281, 'Sitework & Site Utilities');
insert into category (id, name) values (282, 'Electrical');
insert into category (id, name) values (283, 'Waterproofing & Caulking');
insert into category (id, name) values (284, 'Fire Protection');
insert into category (id, name) values (285, 'Roofing (Metal)');
insert into category (id, name) values (286, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (287, 'Termite Control');
insert into category (id, name) values (288, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (289, 'Marlite Panels (FED)');
insert into category (id, name) values (290, 'Framing (Wood)');
insert into category (id, name) values (291, 'Asphalt Paving');
insert into category (id, name) values (292, 'Marlite Panels (FED)');
insert into category (id, name) values (293, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (294, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (295, 'Electrical and Fire Alarm');
insert into category (id, name) values (296, 'RF Shielding');
insert into category (id, name) values (297, 'Plumbing & Medical Gas');
insert into category (id, name) values (298, 'Glass & Glazing');
insert into category (id, name) values (299, 'Wall Protection');
insert into category (id, name) values (300, 'Waterproofing & Caulking');
insert into category (id, name) values (301, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (302, 'Exterior Signage');
insert into category (id, name) values (303, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (304, 'Electrical and Fire Alarm');
insert into category (id, name) values (305, 'Masonry');
insert into category (id, name) values (306, 'Granite Surfaces');
insert into category (id, name) values (307, 'Ornamental Railings');
insert into category (id, name) values (308, 'Epoxy Flooring');
insert into category (id, name) values (309, 'Sitework & Site Utilities');
insert into category (id, name) values (310, 'Glass & Glazing');
insert into category (id, name) values (311, 'EIFS');
insert into category (id, name) values (312, 'Fire Protection');
insert into category (id, name) values (313, 'HVAC');
insert into category (id, name) values (314, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (315, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (316, 'Masonry');
insert into category (id, name) values (317, 'Termite Control');
insert into category (id, name) values (318, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (319, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (320, 'Overhead Doors');
insert into category (id, name) values (321, 'Wall Protection');
insert into category (id, name) values (322, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (323, 'Masonry');
insert into category (id, name) values (324, 'Fire Sprinkler System');
insert into category (id, name) values (325, 'Fire Sprinkler System');
insert into category (id, name) values (326, 'Overhead Doors');
insert into category (id, name) values (327, 'Framing (Steel)');
insert into category (id, name) values (328, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (329, 'Ornamental Railings');
insert into category (id, name) values (330, 'EIFS');
insert into category (id, name) values (331, 'Asphalt Paving');
insert into category (id, name) values (332, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (333, 'Electrical and Fire Alarm');
insert into category (id, name) values (334, 'Curb & Gutter');
insert into category (id, name) values (335, 'Curb & Gutter');
insert into category (id, name) values (336, 'Fire Protection');
insert into category (id, name) values (337, 'Framing (Wood)');
insert into category (id, name) values (338, 'Ornamental Railings');
insert into category (id, name) values (339, 'Site Furnishings');
insert into category (id, name) values (340, 'HVAC');
insert into category (id, name) values (341, 'Epoxy Flooring');
insert into category (id, name) values (342, 'Landscaping & Irrigation');
insert into category (id, name) values (343, 'Roofing (Metal)');
insert into category (id, name) values (344, 'Sitework & Site Utilities');
insert into category (id, name) values (345, 'Electrical and Fire Alarm');
insert into category (id, name) values (346, 'Soft Flooring and Base');
insert into category (id, name) values (347, 'Ornamental Railings');
insert into category (id, name) values (348, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (349, 'Doors, Frames & Hardware');
insert into category (id, name) values (350, 'Framing (Steel)');
insert into category (id, name) values (351, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (352, 'EIFS');
insert into category (id, name) values (353, 'Casework');
insert into category (id, name) values (354, 'Structural & Misc Steel Erection');
insert into category (id, name) values (355, 'Electrical');
insert into category (id, name) values (356, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (357, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (358, 'Fire Sprinkler System');
insert into category (id, name) values (359, 'Doors, Frames & Hardware');
insert into category (id, name) values (360, 'Elevator');
insert into category (id, name) values (361, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (362, 'Roofing (Asphalt)');
insert into category (id, name) values (363, 'Drilled Shafts');
insert into category (id, name) values (364, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (365, 'Masonry & Precast');
insert into category (id, name) values (366, 'Doors, Frames & Hardware');
insert into category (id, name) values (367, 'Wall Protection');
insert into category (id, name) values (368, 'Casework');
insert into category (id, name) values (369, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (370, 'Hard Tile & Stone');
insert into category (id, name) values (371, 'Drilled Shafts');
insert into category (id, name) values (372, 'Marlite Panels (FED)');
insert into category (id, name) values (373, 'Framing (Wood)');
insert into category (id, name) values (374, 'Sitework & Site Utilities');
insert into category (id, name) values (375, 'Framing (Wood)');
insert into category (id, name) values (376, 'Electrical');
insert into category (id, name) values (377, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (378, 'Construction Clean and Final Clean');
insert into category (id, name) values (379, 'Soft Flooring and Base');
insert into category (id, name) values (380, 'Fire Sprinkler System');
insert into category (id, name) values (381, 'Waterproofing & Caulking');
insert into category (id, name) values (382, 'Electrical');
insert into category (id, name) values (383, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (384, 'Roofing (Asphalt)');
insert into category (id, name) values (385, 'Framing (Steel)');
insert into category (id, name) values (386, 'Epoxy Flooring');
insert into category (id, name) values (387, 'Soft Flooring and Base');
insert into category (id, name) values (388, 'Marlite Panels (FED)');
insert into category (id, name) values (389, 'Roofing (Asphalt)');
insert into category (id, name) values (390, 'Plumbing & Medical Gas');
insert into category (id, name) values (391, 'Asphalt Paving');
insert into category (id, name) values (392, 'Glass & Glazing');
insert into category (id, name) values (393, 'Landscaping & Irrigation');
insert into category (id, name) values (394, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (395, 'Marlite Panels (FED)');
insert into category (id, name) values (396, 'Granite Surfaces');
insert into category (id, name) values (397, 'Electrical and Fire Alarm');
insert into category (id, name) values (398, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (399, 'Roofing (Asphalt)');
insert into category (id, name) values (400, 'Sitework & Site Utilities');
insert into category (id, name) values (401, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (402, 'Masonry');
insert into category (id, name) values (403, 'Electrical');
insert into category (id, name) values (404, 'HVAC');
insert into category (id, name) values (405, 'Soft Flooring and Base');
insert into category (id, name) values (406, 'Site Furnishings');
insert into category (id, name) values (407, 'Roofing (Asphalt)');
insert into category (id, name) values (408, 'Glass & Glazing');
insert into category (id, name) values (409, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (410, 'Soft Flooring and Base');
insert into category (id, name) values (411, 'Elevator');
insert into category (id, name) values (412, 'Casework');
insert into category (id, name) values (413, 'Framing (Steel)');
insert into category (id, name) values (414, 'Masonry');
insert into category (id, name) values (415, 'Sitework & Site Utilities');
insert into category (id, name) values (416, 'Structural & Misc Steel Erection');
insert into category (id, name) values (417, 'Masonry & Precast');
insert into category (id, name) values (418, 'HVAC');
insert into category (id, name) values (419, 'Granite Surfaces');
insert into category (id, name) values (420, 'Overhead Doors');
insert into category (id, name) values (421, 'Casework');
insert into category (id, name) values (422, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (423, 'Framing (Wood)');
insert into category (id, name) values (424, 'Fire Sprinkler System');
insert into category (id, name) values (425, 'Epoxy Flooring');
insert into category (id, name) values (426, 'EIFS');
insert into category (id, name) values (427, 'Landscaping & Irrigation');
insert into category (id, name) values (428, 'Overhead Doors');
insert into category (id, name) values (429, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (430, 'HVAC');
insert into category (id, name) values (431, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (432, 'Framing (Steel)');
insert into category (id, name) values (433, 'Drilled Shafts');
insert into category (id, name) values (434, 'Construction Clean and Final Clean');
insert into category (id, name) values (435, 'Roofing (Asphalt)');
insert into category (id, name) values (436, 'Doors, Frames & Hardware');
insert into category (id, name) values (437, 'Fire Sprinkler System');
insert into category (id, name) values (438, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (439, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (440, 'Sitework & Site Utilities');
insert into category (id, name) values (441, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (442, 'Plumbing & Medical Gas');
insert into category (id, name) values (443, 'Ornamental Railings');
insert into category (id, name) values (444, 'Overhead Doors');
insert into category (id, name) values (445, 'Soft Flooring and Base');
insert into category (id, name) values (446, 'Fire Protection');
insert into category (id, name) values (447, 'Overhead Doors');
insert into category (id, name) values (448, 'Roofing (Metal)');
insert into category (id, name) values (449, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (450, 'Casework');
insert into category (id, name) values (451, 'RF Shielding');
insert into category (id, name) values (452, 'Electrical and Fire Alarm');
insert into category (id, name) values (453, 'Roofing (Asphalt)');
insert into category (id, name) values (454, 'Elevator');
insert into category (id, name) values (455, 'Drilled Shafts');
insert into category (id, name) values (456, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (457, 'Waterproofing & Caulking');
insert into category (id, name) values (458, 'Electrical and Fire Alarm');
insert into category (id, name) values (459, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (460, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (461, 'Roofing (Asphalt)');
insert into category (id, name) values (462, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (463, 'Construction Clean and Final Clean');
insert into category (id, name) values (464, 'Fire Sprinkler System');
insert into category (id, name) values (465, 'Exterior Signage');
insert into category (id, name) values (466, 'Hard Tile & Stone');
insert into category (id, name) values (467, 'Masonry');
insert into category (id, name) values (468, 'RF Shielding');
insert into category (id, name) values (469, 'RF Shielding');
insert into category (id, name) values (470, 'Glass & Glazing');
insert into category (id, name) values (471, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (472, 'Wall Protection');
insert into category (id, name) values (473, 'Fire Sprinkler System');
insert into category (id, name) values (474, 'Fire Sprinkler System');
insert into category (id, name) values (475, 'Casework');
insert into category (id, name) values (476, 'Curb & Gutter');
insert into category (id, name) values (477, 'HVAC');
insert into category (id, name) values (478, 'Wall Protection');
insert into category (id, name) values (479, 'Electrical');
insert into category (id, name) values (480, 'RF Shielding');
insert into category (id, name) values (481, 'Epoxy Flooring');
insert into category (id, name) values (482, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (483, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (484, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (485, 'RF Shielding');
insert into category (id, name) values (486, 'Framing (Steel)');
insert into category (id, name) values (487, 'Marlite Panels (FED)');
insert into category (id, name) values (488, 'Exterior Signage');
insert into category (id, name) values (489, 'Termite Control');
insert into category (id, name) values (490, 'Wall Protection');
insert into category (id, name) values (491, 'Site Furnishings');
insert into category (id, name) values (492, 'Wall Protection');
insert into category (id, name) values (493, 'Wall Protection');
insert into category (id, name) values (494, 'Overhead Doors');
insert into category (id, name) values (495, 'Curb & Gutter');
insert into category (id, name) values (496, 'Granite Surfaces');
insert into category (id, name) values (497, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (498, 'Wall Protection');
insert into category (id, name) values (499, 'Doors, Frames & Hardware');
insert into category (id, name) values (500, 'Fire Sprinkler System');
insert into category (id, name) values (501, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (502, 'Construction Clean and Final Clean');
insert into category (id, name) values (503, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (504, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (505, 'Masonry & Precast');
insert into category (id, name) values (506, 'Roofing (Metal)');
insert into category (id, name) values (507, 'Wall Protection');
insert into category (id, name) values (508, 'Overhead Doors');
insert into category (id, name) values (509, 'Asphalt Paving');
insert into category (id, name) values (510, 'Electrical');
insert into category (id, name) values (511, 'Electrical and Fire Alarm');
insert into category (id, name) values (512, 'Plumbing & Medical Gas');
insert into category (id, name) values (513, 'Fire Protection');
insert into category (id, name) values (514, 'Asphalt Paving');
insert into category (id, name) values (515, 'Site Furnishings');
insert into category (id, name) values (516, 'Hard Tile & Stone');
insert into category (id, name) values (517, 'Site Furnishings');
insert into category (id, name) values (518, 'Ornamental Railings');
insert into category (id, name) values (519, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (520, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (521, 'EIFS');
insert into category (id, name) values (522, 'Plumbing & Medical Gas');
insert into category (id, name) values (523, 'Curb & Gutter');
insert into category (id, name) values (524, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (525, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (526, 'Wall Protection');
insert into category (id, name) values (527, 'Hard Tile & Stone');
insert into category (id, name) values (528, 'Epoxy Flooring');
insert into category (id, name) values (529, 'Marlite Panels (FED)');
insert into category (id, name) values (530, 'Curb & Gutter');
insert into category (id, name) values (531, 'Soft Flooring and Base');
insert into category (id, name) values (532, 'Structural & Misc Steel Erection');
insert into category (id, name) values (533, 'Roofing (Metal)');
insert into category (id, name) values (534, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (535, 'Casework');
insert into category (id, name) values (536, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (537, 'Soft Flooring and Base');
insert into category (id, name) values (538, 'Asphalt Paving');
insert into category (id, name) values (539, 'Epoxy Flooring');
insert into category (id, name) values (540, 'Roofing (Metal)');
insert into category (id, name) values (541, 'Roofing (Metal)');
insert into category (id, name) values (542, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (543, 'Glass & Glazing');
insert into category (id, name) values (544, 'Framing (Wood)');
insert into category (id, name) values (545, 'Drilled Shafts');
insert into category (id, name) values (546, 'Plumbing & Medical Gas');
insert into category (id, name) values (547, 'Granite Surfaces');
insert into category (id, name) values (548, 'Doors, Frames & Hardware');
insert into category (id, name) values (549, 'Epoxy Flooring');
insert into category (id, name) values (550, 'Exterior Signage');
insert into category (id, name) values (551, 'Roofing (Asphalt)');
insert into category (id, name) values (552, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (553, 'Framing (Wood)');
insert into category (id, name) values (554, 'Glass & Glazing');
insert into category (id, name) values (555, 'Granite Surfaces');
insert into category (id, name) values (556, 'Construction Clean and Final Clean');
insert into category (id, name) values (557, 'Elevator');
insert into category (id, name) values (558, 'Curb & Gutter');
insert into category (id, name) values (559, 'Masonry & Precast');
insert into category (id, name) values (560, 'Masonry');
insert into category (id, name) values (561, 'Waterproofing & Caulking');
insert into category (id, name) values (562, 'Marlite Panels (FED)');
insert into category (id, name) values (563, 'Construction Clean and Final Clean');
insert into category (id, name) values (564, 'Drilled Shafts');
insert into category (id, name) values (565, 'Marlite Panels (FED)');
insert into category (id, name) values (566, 'Roofing (Asphalt)');
insert into category (id, name) values (567, 'Roofing (Asphalt)');
insert into category (id, name) values (568, 'Granite Surfaces');
insert into category (id, name) values (569, 'Framing (Wood)');
insert into category (id, name) values (570, 'HVAC');
insert into category (id, name) values (571, 'Framing (Wood)');
insert into category (id, name) values (572, 'Elevator');
insert into category (id, name) values (573, 'Hard Tile & Stone');
insert into category (id, name) values (574, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (575, 'Plumbing & Medical Gas');
insert into category (id, name) values (576, 'Soft Flooring and Base');
insert into category (id, name) values (577, 'Drilled Shafts');
insert into category (id, name) values (578, 'Glass & Glazing');
insert into category (id, name) values (579, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (580, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (581, 'Masonry');
insert into category (id, name) values (582, 'Granite Surfaces');
insert into category (id, name) values (583, 'Fire Protection');
insert into category (id, name) values (584, 'RF Shielding');
insert into category (id, name) values (585, 'Elevator');
insert into category (id, name) values (586, 'Ornamental Railings');
insert into category (id, name) values (587, 'HVAC');
insert into category (id, name) values (588, 'Site Furnishings');
insert into category (id, name) values (589, 'Masonry');
insert into category (id, name) values (590, 'Curb & Gutter');
insert into category (id, name) values (591, 'Curb & Gutter');
insert into category (id, name) values (592, 'Plumbing & Medical Gas');
insert into category (id, name) values (593, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (594, 'Exterior Signage');
insert into category (id, name) values (595, 'Roofing (Metal)');
insert into category (id, name) values (596, 'Construction Clean and Final Clean');
insert into category (id, name) values (597, 'Soft Flooring and Base');
insert into category (id, name) values (598, 'Masonry & Precast');
insert into category (id, name) values (599, 'Masonry');
insert into category (id, name) values (600, 'Ornamental Railings');
insert into category (id, name) values (601, 'Overhead Doors');
insert into category (id, name) values (602, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (603, 'Electrical and Fire Alarm');
insert into category (id, name) values (604, 'Termite Control');
insert into category (id, name) values (605, 'Plumbing & Medical Gas');
insert into category (id, name) values (606, 'Ornamental Railings');
insert into category (id, name) values (607, 'Framing (Steel)');
insert into category (id, name) values (608, 'Exterior Signage');
insert into category (id, name) values (609, 'Roofing (Metal)');
insert into category (id, name) values (610, 'Construction Clean and Final Clean');
insert into category (id, name) values (611, 'Landscaping & Irrigation');
insert into category (id, name) values (612, 'Roofing (Metal)');
insert into category (id, name) values (613, 'Masonry');
insert into category (id, name) values (614, 'Construction Clean and Final Clean');
insert into category (id, name) values (615, 'Termite Control');
insert into category (id, name) values (616, 'Soft Flooring and Base');
insert into category (id, name) values (617, 'Sitework & Site Utilities');
insert into category (id, name) values (618, 'HVAC');
insert into category (id, name) values (619, 'Roofing (Metal)');
insert into category (id, name) values (620, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (621, 'Hard Tile & Stone');
insert into category (id, name) values (622, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (623, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (624, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (625, 'Glass & Glazing');
insert into category (id, name) values (626, 'HVAC');
insert into category (id, name) values (627, 'Site Furnishings');
insert into category (id, name) values (628, 'Masonry & Precast');
insert into category (id, name) values (629, 'Overhead Doors');
insert into category (id, name) values (630, 'Fire Protection');
insert into category (id, name) values (631, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (632, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (633, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (634, 'Epoxy Flooring');
insert into category (id, name) values (635, 'Doors, Frames & Hardware');
insert into category (id, name) values (636, 'Framing (Wood)');
insert into category (id, name) values (637, 'Roofing (Asphalt)');
insert into category (id, name) values (638, 'Glass & Glazing');
insert into category (id, name) values (639, 'Marlite Panels (FED)');
insert into category (id, name) values (640, 'Plumbing & Medical Gas');
insert into category (id, name) values (641, 'Hard Tile & Stone');
insert into category (id, name) values (642, 'Casework');
insert into category (id, name) values (643, 'Glass & Glazing');
insert into category (id, name) values (644, 'Granite Surfaces');
insert into category (id, name) values (645, 'Glass & Glazing');
insert into category (id, name) values (646, 'Waterproofing & Caulking');
insert into category (id, name) values (647, 'Soft Flooring and Base');
insert into category (id, name) values (648, 'Curb & Gutter');
insert into category (id, name) values (649, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (650, 'Plumbing & Medical Gas');
insert into category (id, name) values (651, 'HVAC');
insert into category (id, name) values (652, 'Roofing (Metal)');
insert into category (id, name) values (653, 'RF Shielding');
insert into category (id, name) values (654, 'Overhead Doors');
insert into category (id, name) values (655, 'Sitework & Site Utilities');
insert into category (id, name) values (656, 'Fire Sprinkler System');
insert into category (id, name) values (657, 'Structural & Misc Steel Erection');
insert into category (id, name) values (658, 'Site Furnishings');
insert into category (id, name) values (659, 'Epoxy Flooring');
insert into category (id, name) values (660, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (661, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (662, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (663, 'Overhead Doors');
insert into category (id, name) values (664, 'EIFS');
insert into category (id, name) values (665, 'Doors, Frames & Hardware');
insert into category (id, name) values (666, 'Casework');
insert into category (id, name) values (667, 'Wall Protection');
insert into category (id, name) values (668, 'Sitework & Site Utilities');
insert into category (id, name) values (669, 'Overhead Doors');
insert into category (id, name) values (670, 'Drilled Shafts');
insert into category (id, name) values (671, 'Site Furnishings');
insert into category (id, name) values (672, 'Plumbing & Medical Gas');
insert into category (id, name) values (673, 'Granite Surfaces');
insert into category (id, name) values (674, 'Exterior Signage');
insert into category (id, name) values (675, 'Marlite Panels (FED)');
insert into category (id, name) values (676, 'Site Furnishings');
insert into category (id, name) values (677, 'Electrical and Fire Alarm');
insert into category (id, name) values (678, 'Plumbing & Medical Gas');
insert into category (id, name) values (679, 'Ornamental Railings');
insert into category (id, name) values (680, 'Roofing (Asphalt)');
insert into category (id, name) values (681, 'Epoxy Flooring');
insert into category (id, name) values (682, 'Masonry');
insert into category (id, name) values (683, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (684, 'Drilled Shafts');
insert into category (id, name) values (685, 'HVAC');
insert into category (id, name) values (686, 'Framing (Wood)');
insert into category (id, name) values (687, 'Masonry & Precast');
insert into category (id, name) values (688, 'Epoxy Flooring');
insert into category (id, name) values (689, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (690, 'Exterior Signage');
insert into category (id, name) values (691, 'Structural & Misc Steel Erection');
insert into category (id, name) values (692, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (693, 'Drilled Shafts');
insert into category (id, name) values (694, 'Asphalt Paving');
insert into category (id, name) values (695, 'Asphalt Paving');
insert into category (id, name) values (696, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (697, 'Curb & Gutter');
insert into category (id, name) values (698, 'Drilled Shafts');
insert into category (id, name) values (699, 'Drilled Shafts');
insert into category (id, name) values (700, 'HVAC');
insert into category (id, name) values (701, 'Overhead Doors');
insert into category (id, name) values (702, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (703, 'Ornamental Railings');
insert into category (id, name) values (704, 'Epoxy Flooring');
insert into category (id, name) values (705, 'Framing (Wood)');
insert into category (id, name) values (706, 'EIFS');
insert into category (id, name) values (707, 'Roofing (Metal)');
insert into category (id, name) values (708, 'Framing (Steel)');
insert into category (id, name) values (709, 'Fire Sprinkler System');
insert into category (id, name) values (710, 'Landscaping & Irrigation');
insert into category (id, name) values (711, 'Marlite Panels (FED)');
insert into category (id, name) values (712, 'Granite Surfaces');
insert into category (id, name) values (713, 'Waterproofing & Caulking');
insert into category (id, name) values (714, 'Roofing (Metal)');
insert into category (id, name) values (715, 'Framing (Wood)');
insert into category (id, name) values (716, 'Marlite Panels (FED)');
insert into category (id, name) values (717, 'Fire Protection');
insert into category (id, name) values (718, 'Termite Control');
insert into category (id, name) values (719, 'Exterior Signage');
insert into category (id, name) values (720, 'Sitework & Site Utilities');
insert into category (id, name) values (721, 'Hard Tile & Stone');
insert into category (id, name) values (722, 'Doors, Frames & Hardware');
insert into category (id, name) values (723, 'Electrical');
insert into category (id, name) values (724, 'Drilled Shafts');
insert into category (id, name) values (725, 'Electrical');
insert into category (id, name) values (726, 'Landscaping & Irrigation');
insert into category (id, name) values (727, 'Drilled Shafts');
insert into category (id, name) values (728, 'Asphalt Paving');
insert into category (id, name) values (729, 'Waterproofing & Caulking');
insert into category (id, name) values (730, 'Fire Sprinkler System');
insert into category (id, name) values (731, 'Marlite Panels (FED)');
insert into category (id, name) values (732, 'Fire Protection');
insert into category (id, name) values (733, 'Curb & Gutter');
insert into category (id, name) values (734, 'HVAC');
insert into category (id, name) values (735, 'Epoxy Flooring');
insert into category (id, name) values (736, 'Masonry & Precast');
insert into category (id, name) values (737, 'RF Shielding');
insert into category (id, name) values (738, 'Casework');
insert into category (id, name) values (739, 'Framing (Steel)');
insert into category (id, name) values (740, 'Framing (Steel)');
insert into category (id, name) values (741, 'RF Shielding');
insert into category (id, name) values (742, 'Elevator');
insert into category (id, name) values (743, 'Framing (Wood)');
insert into category (id, name) values (744, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (745, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (746, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (747, 'Site Furnishings');
insert into category (id, name) values (748, 'Site Furnishings');
insert into category (id, name) values (749, 'Glass & Glazing');
insert into category (id, name) values (750, 'Casework');
insert into category (id, name) values (751, 'Ornamental Railings');
insert into category (id, name) values (752, 'Curb & Gutter');
insert into category (id, name) values (753, 'Exterior Signage');
insert into category (id, name) values (754, 'Framing (Steel)');
insert into category (id, name) values (755, 'Waterproofing & Caulking');
insert into category (id, name) values (756, 'Casework');
insert into category (id, name) values (757, 'Roofing (Metal)');
insert into category (id, name) values (758, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (759, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (760, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (761, 'EIFS');
insert into category (id, name) values (762, 'Site Furnishings');
insert into category (id, name) values (763, 'Casework');
insert into category (id, name) values (764, 'Soft Flooring and Base');
insert into category (id, name) values (765, 'Curb & Gutter');
insert into category (id, name) values (766, 'Electrical');
insert into category (id, name) values (767, 'Waterproofing & Caulking');
insert into category (id, name) values (768, 'Structural & Misc Steel Erection');
insert into category (id, name) values (769, 'EIFS');
insert into category (id, name) values (770, 'Doors, Frames & Hardware');
insert into category (id, name) values (771, 'Doors, Frames & Hardware');
insert into category (id, name) values (772, 'Asphalt Paving');
insert into category (id, name) values (773, 'Hard Tile & Stone');
insert into category (id, name) values (774, 'Masonry & Precast');
insert into category (id, name) values (775, 'Ornamental Railings');
insert into category (id, name) values (776, 'Ornamental Railings');
insert into category (id, name) values (777, 'Epoxy Flooring');
insert into category (id, name) values (778, 'Soft Flooring and Base');
insert into category (id, name) values (779, 'Elevator');
insert into category (id, name) values (780, 'Waterproofing & Caulking');
insert into category (id, name) values (781, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (782, 'Wall Protection');
insert into category (id, name) values (783, 'Ornamental Railings');
insert into category (id, name) values (784, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (785, 'Soft Flooring and Base');
insert into category (id, name) values (786, 'Roofing (Metal)');
insert into category (id, name) values (787, 'Casework');
insert into category (id, name) values (788, 'Curb & Gutter');
insert into category (id, name) values (789, 'HVAC');
insert into category (id, name) values (790, 'HVAC');
insert into category (id, name) values (791, 'Structural & Misc Steel Erection');
insert into category (id, name) values (792, 'Glass & Glazing');
insert into category (id, name) values (793, 'RF Shielding');
insert into category (id, name) values (794, 'Construction Clean and Final Clean');
insert into category (id, name) values (795, 'Glass & Glazing');
insert into category (id, name) values (796, 'Construction Clean and Final Clean');
insert into category (id, name) values (797, 'Ornamental Railings');
insert into category (id, name) values (798, 'Fire Sprinkler System');
insert into category (id, name) values (799, 'Landscaping & Irrigation');
insert into category (id, name) values (800, 'Landscaping & Irrigation');
insert into category (id, name) values (801, 'EIFS');
insert into category (id, name) values (802, 'Wall Protection');
insert into category (id, name) values (803, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (804, 'Fire Protection');
insert into category (id, name) values (805, 'Ornamental Railings');
insert into category (id, name) values (806, 'Roofing (Metal)');
insert into category (id, name) values (807, 'Drilled Shafts');
insert into category (id, name) values (808, 'Doors, Frames & Hardware');
insert into category (id, name) values (809, 'Wall Protection');
insert into category (id, name) values (810, 'Landscaping & Irrigation');
insert into category (id, name) values (811, 'Roofing (Asphalt)');
insert into category (id, name) values (812, 'Electrical and Fire Alarm');
insert into category (id, name) values (813, 'Overhead Doors');
insert into category (id, name) values (814, 'Sitework & Site Utilities');
insert into category (id, name) values (815, 'Doors, Frames & Hardware');
insert into category (id, name) values (816, 'Doors, Frames & Hardware');
insert into category (id, name) values (817, 'Sitework & Site Utilities');
insert into category (id, name) values (818, 'Site Furnishings');
insert into category (id, name) values (819, 'Fire Protection');
insert into category (id, name) values (820, 'Framing (Wood)');
insert into category (id, name) values (821, 'Framing (Wood)');
insert into category (id, name) values (822, 'Fire Protection');
insert into category (id, name) values (823, 'Plumbing & Medical Gas');
insert into category (id, name) values (824, 'Construction Clean and Final Clean');
insert into category (id, name) values (825, 'Landscaping & Irrigation');
insert into category (id, name) values (826, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (827, 'Fire Sprinkler System');
insert into category (id, name) values (828, 'Masonry & Precast');
insert into category (id, name) values (829, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (830, 'Curb & Gutter');
insert into category (id, name) values (831, 'Wall Protection');
insert into category (id, name) values (832, 'RF Shielding');
insert into category (id, name) values (833, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (834, 'Waterproofing & Caulking');
insert into category (id, name) values (835, 'Exterior Signage');
insert into category (id, name) values (836, 'Waterproofing & Caulking');
insert into category (id, name) values (837, 'Marlite Panels (FED)');
insert into category (id, name) values (838, 'Landscaping & Irrigation');
insert into category (id, name) values (839, 'HVAC');
insert into category (id, name) values (840, 'Masonry & Precast');
insert into category (id, name) values (841, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (842, 'Plumbing & Medical Gas');
insert into category (id, name) values (843, 'Epoxy Flooring');
insert into category (id, name) values (844, 'Electrical and Fire Alarm');
insert into category (id, name) values (845, 'Hard Tile & Stone');
insert into category (id, name) values (846, 'Sitework & Site Utilities');
insert into category (id, name) values (847, 'EIFS');
insert into category (id, name) values (848, 'Elevator');
insert into category (id, name) values (849, 'RF Shielding');
insert into category (id, name) values (850, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (851, 'Landscaping & Irrigation');
insert into category (id, name) values (852, 'Exterior Signage');
insert into category (id, name) values (853, 'EIFS');
insert into category (id, name) values (854, 'Termite Control');
insert into category (id, name) values (855, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (856, 'Structural & Misc Steel Erection');
insert into category (id, name) values (857, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (858, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (859, 'Site Furnishings');
insert into category (id, name) values (860, 'Site Furnishings');
insert into category (id, name) values (861, 'Glass & Glazing');
insert into category (id, name) values (862, 'Asphalt Paving');
insert into category (id, name) values (863, 'Masonry');
insert into category (id, name) values (864, 'Roofing (Asphalt)');
insert into category (id, name) values (865, 'Structural & Misc Steel Erection');
insert into category (id, name) values (866, 'Site Furnishings');
insert into category (id, name) values (867, 'Framing (Wood)');
insert into category (id, name) values (868, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (869, 'EIFS');
insert into category (id, name) values (870, 'Fire Protection');
insert into category (id, name) values (871, 'Marlite Panels (FED)');
insert into category (id, name) values (872, 'RF Shielding');
insert into category (id, name) values (873, 'RF Shielding');
insert into category (id, name) values (874, 'Fire Protection');
insert into category (id, name) values (875, 'Wall Protection');
insert into category (id, name) values (876, 'Electrical');
insert into category (id, name) values (877, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (878, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (879, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (880, 'Sitework & Site Utilities');
insert into category (id, name) values (881, 'RF Shielding');
insert into category (id, name) values (882, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (883, 'Glass & Glazing');
insert into category (id, name) values (884, 'Site Furnishings');
insert into category (id, name) values (885, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (886, 'Fire Sprinkler System');
insert into category (id, name) values (887, 'Curb & Gutter');
insert into category (id, name) values (888, 'Roofing (Metal)');
insert into category (id, name) values (889, 'Exterior Signage');
insert into category (id, name) values (890, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (891, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (892, 'Hard Tile & Stone');
insert into category (id, name) values (893, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (894, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (895, 'Granite Surfaces');
insert into category (id, name) values (896, 'Electrical and Fire Alarm');
insert into category (id, name) values (897, 'Casework');
insert into category (id, name) values (898, 'Marlite Panels (FED)');
insert into category (id, name) values (899, 'RF Shielding');
insert into category (id, name) values (900, 'Site Furnishings');
insert into category (id, name) values (901, 'Exterior Signage');
insert into category (id, name) values (902, 'Hard Tile & Stone');
insert into category (id, name) values (903, 'Curb & Gutter');
insert into category (id, name) values (904, 'Masonry');
insert into category (id, name) values (905, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (906, 'Granite Surfaces');
insert into category (id, name) values (907, 'Exterior Signage');
insert into category (id, name) values (908, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (909, 'Epoxy Flooring');
insert into category (id, name) values (910, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (911, 'Soft Flooring and Base');
insert into category (id, name) values (912, 'Glass & Glazing');
insert into category (id, name) values (913, 'Electrical and Fire Alarm');
insert into category (id, name) values (914, 'Plumbing & Medical Gas');
insert into category (id, name) values (915, 'Site Furnishings');
insert into category (id, name) values (916, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (917, 'Masonry & Precast');
insert into category (id, name) values (918, 'Ornamental Railings');
insert into category (id, name) values (919, 'Ornamental Railings');
insert into category (id, name) values (920, 'Marlite Panels (FED)');
insert into category (id, name) values (921, 'Termite Control');
insert into category (id, name) values (922, 'Fire Protection');
insert into category (id, name) values (923, 'Structural and Misc Steel (Fabrication)');
insert into category (id, name) values (924, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (925, 'Wall Protection');
insert into category (id, name) values (926, 'RF Shielding');
insert into category (id, name) values (927, 'Termite Control');
insert into category (id, name) values (928, 'Epoxy Flooring');
insert into category (id, name) values (929, 'Epoxy Flooring');
insert into category (id, name) values (930, 'Sitework & Site Utilities');
insert into category (id, name) values (931, 'Fire Protection');
insert into category (id, name) values (932, 'Curb & Gutter');
insert into category (id, name) values (933, 'Construction Clean and Final Clean');
insert into category (id, name) values (934, 'Hard Tile & Stone');
insert into category (id, name) values (935, 'Exterior Signage');
insert into category (id, name) values (936, 'Landscaping & Irrigation');
insert into category (id, name) values (937, 'Roofing (Metal)');
insert into category (id, name) values (938, 'Elevator');
insert into category (id, name) values (939, 'Landscaping & Irrigation');
insert into category (id, name) values (940, 'Fire Sprinkler System');
insert into category (id, name) values (941, 'Wall Protection');
insert into category (id, name) values (942, 'Waterproofing & Caulking');
insert into category (id, name) values (943, 'Roofing (Metal)');
insert into category (id, name) values (944, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (945, 'Drilled Shafts');
insert into category (id, name) values (946, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (947, 'Retaining Wall and Brick Pavers');
insert into category (id, name) values (948, 'Marlite Panels (FED)');
insert into category (id, name) values (949, 'Ornamental Railings');
insert into category (id, name) values (950, 'Exterior Signage');
insert into category (id, name) values (951, 'Drywall & Acoustical (FED)');
insert into category (id, name) values (952, 'Framing (Steel)');
insert into category (id, name) values (953, 'Epoxy Flooring');
insert into category (id, name) values (954, 'Curb & Gutter');
insert into category (id, name) values (955, 'Fire Protection');
insert into category (id, name) values (956, 'Granite Surfaces');
insert into category (id, name) values (957, 'Waterproofing & Caulking');
insert into category (id, name) values (958, 'Termite Control');
insert into category (id, name) values (959, 'Wall Protection');
insert into category (id, name) values (960, 'Landscaping & Irrigation');
insert into category (id, name) values (961, 'EIFS');
insert into category (id, name) values (962, 'Drilled Shafts');
insert into category (id, name) values (963, 'Framing (Steel)');
insert into category (id, name) values (964, 'Fire Protection');
insert into category (id, name) values (965, 'Roofing (Asphalt)');
insert into category (id, name) values (966, 'Drywall & Acoustical (MOB)');
insert into category (id, name) values (967, 'Asphalt Paving');
insert into category (id, name) values (968, 'Painting & Vinyl Wall Covering');
insert into category (id, name) values (969, 'Hard Tile & Stone');
insert into category (id, name) values (970, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (id, name) values (971, 'Epoxy Flooring');
insert into category (id, name) values (972, 'Prefabricated Aluminum Metal Canopies');
insert into category (id, name) values (973, 'EIFS');
insert into category (id, name) values (974, 'Waterproofing & Caulking');
insert into category (id, name) values (975, 'Asphalt Paving');
insert into category (id, name) values (976, 'Granite Surfaces');
insert into category (id, name) values (977, 'Fire Protection');
insert into category (id, name) values (978, 'Epoxy Flooring');
insert into category (id, name) values (979, 'Asphalt Paving');
insert into category (id, name) values (980, 'Casework');
insert into category (id, name) values (981, 'Roofing (Metal)');
insert into category (id, name) values (982, 'Electrical');
insert into category (id, name) values (983, 'RF Shielding');
insert into category (id, name) values (984, 'Waterproofing & Caulking');
insert into category (id, name) values (985, 'Electrical and Fire Alarm');
insert into category (id, name) values (986, 'Granite Surfaces');
insert into category (id, name) values (987, 'Curb & Gutter');
insert into category (id, name) values (988, 'Epoxy Flooring');
insert into category (id, name) values (989, 'Sitework & Site Utilities');
insert into category (id, name) values (990, 'Roofing (Asphalt)');
insert into category (id, name) values (991, 'Rebar & Wire Mesh Install');
insert into category (id, name) values (992, 'Granite Surfaces');
insert into category (id, name) values (993, 'Doors, Frames & Hardware');
insert into category (id, name) values (994, 'Sitework & Site Utilities');
insert into category (id, name) values (995, 'Drilled Shafts');
insert into category (id, name) values (996, 'Site Furnishings');
insert into category (id, name) values (997, 'Landscaping & Irrigation');
insert into category (id, name) values (998, 'Waterproofing & Caulking');
insert into category (id, name) values (999, 'Exterior Signage');
insert into category (id, name) values (1000, 'Construction Clean and Final Clean');
