DROP TABLE IF EXISTS role;
CREATE TABLE role (
	id INT AUTO_INCREMENT NOT NULL,
	name VARCHAR(50) NOT NULL,

    PRIMARY KEY (id)
);

insert into role (id, name) values (1, 'Supervisor');
insert into role (id, name) values (2, 'Surveyor');
insert into role (id, name) values (3, 'Supervisor');
insert into role (id, name) values (4, 'Subcontractor');
insert into role (id, name) values (5, 'Electrician');
insert into role (id, name) values (6, 'Construction Worker');
insert into role (id, name) values (7, 'Surveyor');
insert into role (id, name) values (8, 'Construction Worker');
insert into role (id, name) values (9, 'Supervisor');
insert into role (id, name) values (10, 'Project Manager');
insert into role (id, name) values (11, 'Architect');
insert into role (id, name) values (12, 'Subcontractor');
insert into role (id, name) values (13, 'Construction Foreman');
insert into role (id, name) values (14, 'Supervisor');
insert into role (id, name) values (15, 'Electrician');
insert into role (id, name) values (16, 'Estimator');
insert into role (id, name) values (17, 'Estimator');
insert into role (id, name) values (18, 'Supervisor');
insert into role (id, name) values (19, 'Subcontractor');
insert into role (id, name) values (20, 'Construction Expeditor');
insert into role (id, name) values (21, 'Surveyor');
insert into role (id, name) values (22, 'Construction Foreman');
insert into role (id, name) values (23, 'Construction Manager');
insert into role (id, name) values (24, 'Electrician');
insert into role (id, name) values (25, 'Subcontractor');
insert into role (id, name) values (26, 'Estimator');
insert into role (id, name) values (27, 'Supervisor');
insert into role (id, name) values (28, 'Estimator');
insert into role (id, name) values (29, 'Project Manager');
insert into role (id, name) values (30, 'Supervisor');
insert into role (id, name) values (31, 'Surveyor');
insert into role (id, name) values (32, 'Construction Expeditor');
insert into role (id, name) values (33, 'Supervisor');
insert into role (id, name) values (34, 'Estimator');
insert into role (id, name) values (35, 'Supervisor');
insert into role (id, name) values (36, 'Project Manager');
insert into role (id, name) values (37, 'Construction Worker');
insert into role (id, name) values (38, 'Construction Expeditor');
insert into role (id, name) values (39, 'Construction Expeditor');
insert into role (id, name) values (40, 'Construction Worker');
insert into role (id, name) values (41, 'Construction Foreman');
insert into role (id, name) values (42, 'Construction Worker');
insert into role (id, name) values (43, 'Subcontractor');
insert into role (id, name) values (44, 'Engineer');
insert into role (id, name) values (45, 'Subcontractor');
insert into role (id, name) values (46, 'Project Manager');
insert into role (id, name) values (47, 'Surveyor');
insert into role (id, name) values (48, 'Construction Expeditor');
insert into role (id, name) values (49, 'Construction Expeditor');
insert into role (id, name) values (50, 'Subcontractor');
insert into role (id, name) values (51, 'Electrician');
insert into role (id, name) values (52, 'Construction Manager');
insert into role (id, name) values (53, 'Construction Expeditor');
insert into role (id, name) values (54, 'Construction Foreman');
insert into role (id, name) values (55, 'Engineer');
insert into role (id, name) values (56, 'Estimator');
insert into role (id, name) values (57, 'Surveyor');
insert into role (id, name) values (58, 'Construction Manager');
insert into role (id, name) values (59, 'Construction Manager');
insert into role (id, name) values (60, 'Supervisor');
insert into role (id, name) values (61, 'Surveyor');
insert into role (id, name) values (62, 'Subcontractor');
insert into role (id, name) values (63, 'Project Manager');
insert into role (id, name) values (64, 'Subcontractor');
insert into role (id, name) values (65, 'Engineer');
insert into role (id, name) values (66, 'Surveyor');
insert into role (id, name) values (67, 'Surveyor');
insert into role (id, name) values (68, 'Supervisor');
insert into role (id, name) values (69, 'Surveyor');
insert into role (id, name) values (70, 'Architect');
insert into role (id, name) values (71, 'Estimator');
insert into role (id, name) values (72, 'Construction Manager');
insert into role (id, name) values (73, 'Construction Foreman');
insert into role (id, name) values (74, 'Surveyor');
insert into role (id, name) values (75, 'Surveyor');
insert into role (id, name) values (76, 'Construction Worker');
insert into role (id, name) values (77, 'Construction Manager');
insert into role (id, name) values (78, 'Construction Worker');
insert into role (id, name) values (79, 'Subcontractor');
insert into role (id, name) values (80, 'Architect');
insert into role (id, name) values (81, 'Supervisor');
insert into role (id, name) values (82, 'Supervisor');
insert into role (id, name) values (83, 'Construction Expeditor');
insert into role (id, name) values (84, 'Subcontractor');
insert into role (id, name) values (85, 'Estimator');
insert into role (id, name) values (86, 'Construction Worker');
insert into role (id, name) values (87, 'Construction Foreman');
insert into role (id, name) values (88, 'Estimator');
insert into role (id, name) values (89, 'Engineer');
insert into role (id, name) values (90, 'Supervisor');
insert into role (id, name) values (91, 'Subcontractor');
insert into role (id, name) values (92, 'Subcontractor');
insert into role (id, name) values (93, 'Engineer');
insert into role (id, name) values (94, 'Electrician');
insert into role (id, name) values (95, 'Supervisor');
insert into role (id, name) values (96, 'Subcontractor');
insert into role (id, name) values (97, 'Electrician');
insert into role (id, name) values (98, 'Electrician');
insert into role (id, name) values (99, 'Project Manager');
insert into role (id, name) values (100, 'Subcontractor');
insert into role (id, name) values (101, 'Surveyor');
insert into role (id, name) values (102, 'Construction Expeditor');
insert into role (id, name) values (103, 'Engineer');
insert into role (id, name) values (104, 'Electrician');
insert into role (id, name) values (105, 'Surveyor');
insert into role (id, name) values (106, 'Architect');
insert into role (id, name) values (107, 'Construction Manager');
insert into role (id, name) values (108, 'Surveyor');
insert into role (id, name) values (109, 'Subcontractor');
insert into role (id, name) values (110, 'Supervisor');
insert into role (id, name) values (111, 'Construction Worker');
insert into role (id, name) values (112, 'Project Manager');
insert into role (id, name) values (113, 'Subcontractor');
insert into role (id, name) values (114, 'Surveyor');
insert into role (id, name) values (115, 'Subcontractor');
insert into role (id, name) values (116, 'Architect');
insert into role (id, name) values (117, 'Estimator');
insert into role (id, name) values (118, 'Supervisor');
insert into role (id, name) values (119, 'Estimator');
insert into role (id, name) values (120, 'Construction Manager');
insert into role (id, name) values (121, 'Construction Manager');
insert into role (id, name) values (122, 'Construction Foreman');
insert into role (id, name) values (123, 'Engineer');
insert into role (id, name) values (124, 'Engineer');
insert into role (id, name) values (125, 'Engineer');
insert into role (id, name) values (126, 'Construction Expeditor');
insert into role (id, name) values (127, 'Project Manager');
insert into role (id, name) values (128, 'Construction Manager');
insert into role (id, name) values (129, 'Architect');
insert into role (id, name) values (130, 'Construction Expeditor');
insert into role (id, name) values (131, 'Estimator');
insert into role (id, name) values (132, 'Engineer');
insert into role (id, name) values (133, 'Construction Worker');
insert into role (id, name) values (134, 'Construction Manager');
insert into role (id, name) values (135, 'Construction Foreman');
insert into role (id, name) values (136, 'Estimator');
insert into role (id, name) values (137, 'Construction Manager');
insert into role (id, name) values (138, 'Construction Foreman');
insert into role (id, name) values (139, 'Electrician');
insert into role (id, name) values (140, 'Subcontractor');
insert into role (id, name) values (141, 'Electrician');
insert into role (id, name) values (142, 'Architect');
insert into role (id, name) values (143, 'Subcontractor');
insert into role (id, name) values (144, 'Construction Worker');
insert into role (id, name) values (145, 'Supervisor');
insert into role (id, name) values (146, 'Engineer');
insert into role (id, name) values (147, 'Construction Expeditor');
insert into role (id, name) values (148, 'Project Manager');
insert into role (id, name) values (149, 'Electrician');
insert into role (id, name) values (150, 'Surveyor');
insert into role (id, name) values (151, 'Construction Manager');
insert into role (id, name) values (152, 'Construction Worker');
insert into role (id, name) values (153, 'Construction Foreman');
insert into role (id, name) values (154, 'Engineer');
insert into role (id, name) values (155, 'Construction Manager');
insert into role (id, name) values (156, 'Architect');
insert into role (id, name) values (157, 'Supervisor');
insert into role (id, name) values (158, 'Engineer');
insert into role (id, name) values (159, 'Architect');
insert into role (id, name) values (160, 'Subcontractor');
insert into role (id, name) values (161, 'Architect');
insert into role (id, name) values (162, 'Electrician');
insert into role (id, name) values (163, 'Architect');
insert into role (id, name) values (164, 'Electrician');
insert into role (id, name) values (165, 'Construction Foreman');
insert into role (id, name) values (166, 'Construction Foreman');
insert into role (id, name) values (167, 'Project Manager');
insert into role (id, name) values (168, 'Construction Foreman');
insert into role (id, name) values (169, 'Architect');
insert into role (id, name) values (170, 'Construction Foreman');
insert into role (id, name) values (171, 'Subcontractor');
insert into role (id, name) values (172, 'Supervisor');
insert into role (id, name) values (173, 'Estimator');
insert into role (id, name) values (174, 'Architect');
insert into role (id, name) values (175, 'Estimator');
insert into role (id, name) values (176, 'Construction Foreman');
insert into role (id, name) values (177, 'Subcontractor');
insert into role (id, name) values (178, 'Electrician');
insert into role (id, name) values (179, 'Estimator');
insert into role (id, name) values (180, 'Electrician');
insert into role (id, name) values (181, 'Construction Worker');
insert into role (id, name) values (182, 'Engineer');
insert into role (id, name) values (183, 'Subcontractor');
insert into role (id, name) values (184, 'Construction Worker');
insert into role (id, name) values (185, 'Supervisor');
insert into role (id, name) values (186, 'Supervisor');
insert into role (id, name) values (187, 'Surveyor');
insert into role (id, name) values (188, 'Construction Expeditor');
insert into role (id, name) values (189, 'Construction Expeditor');
insert into role (id, name) values (190, 'Construction Manager');
insert into role (id, name) values (191, 'Supervisor');
insert into role (id, name) values (192, 'Surveyor');
insert into role (id, name) values (193, 'Estimator');
insert into role (id, name) values (194, 'Electrician');
insert into role (id, name) values (195, 'Construction Manager');
insert into role (id, name) values (196, 'Supervisor');
insert into role (id, name) values (197, 'Electrician');
insert into role (id, name) values (198, 'Construction Manager');
insert into role (id, name) values (199, 'Project Manager');
insert into role (id, name) values (200, 'Construction Foreman');
insert into role (id, name) values (201, 'Engineer');
insert into role (id, name) values (202, 'Supervisor');
insert into role (id, name) values (203, 'Engineer');
insert into role (id, name) values (204, 'Construction Foreman');
insert into role (id, name) values (205, 'Electrician');
insert into role (id, name) values (206, 'Electrician');
insert into role (id, name) values (207, 'Construction Manager');
insert into role (id, name) values (208, 'Construction Worker');
insert into role (id, name) values (209, 'Construction Manager');
insert into role (id, name) values (210, 'Supervisor');
insert into role (id, name) values (211, 'Engineer');
insert into role (id, name) values (212, 'Construction Worker');
insert into role (id, name) values (213, 'Project Manager');
insert into role (id, name) values (214, 'Surveyor');
insert into role (id, name) values (215, 'Subcontractor');
insert into role (id, name) values (216, 'Construction Foreman');
insert into role (id, name) values (217, 'Construction Foreman');
insert into role (id, name) values (218, 'Estimator');
insert into role (id, name) values (219, 'Architect');
insert into role (id, name) values (220, 'Surveyor');
insert into role (id, name) values (221, 'Project Manager');
insert into role (id, name) values (222, 'Subcontractor');
insert into role (id, name) values (223, 'Estimator');
insert into role (id, name) values (224, 'Supervisor');
insert into role (id, name) values (225, 'Construction Expeditor');
insert into role (id, name) values (226, 'Surveyor');
insert into role (id, name) values (227, 'Architect');
insert into role (id, name) values (228, 'Subcontractor');
insert into role (id, name) values (229, 'Construction Worker');
insert into role (id, name) values (230, 'Electrician');
insert into role (id, name) values (231, 'Engineer');
insert into role (id, name) values (232, 'Project Manager');
insert into role (id, name) values (233, 'Construction Expeditor');
insert into role (id, name) values (234, 'Subcontractor');
insert into role (id, name) values (235, 'Engineer');
insert into role (id, name) values (236, 'Estimator');
insert into role (id, name) values (237, 'Surveyor');
insert into role (id, name) values (238, 'Supervisor');
insert into role (id, name) values (239, 'Construction Worker');
insert into role (id, name) values (240, 'Construction Worker');
insert into role (id, name) values (241, 'Construction Expeditor');
insert into role (id, name) values (242, 'Engineer');
insert into role (id, name) values (243, 'Construction Worker');
insert into role (id, name) values (244, 'Construction Expeditor');
insert into role (id, name) values (245, 'Construction Foreman');
insert into role (id, name) values (246, 'Construction Expeditor');
insert into role (id, name) values (247, 'Estimator');
insert into role (id, name) values (248, 'Architect');
insert into role (id, name) values (249, 'Electrician');
insert into role (id, name) values (250, 'Estimator');
insert into role (id, name) values (251, 'Subcontractor');
insert into role (id, name) values (252, 'Construction Manager');
insert into role (id, name) values (253, 'Supervisor');
insert into role (id, name) values (254, 'Construction Worker');
insert into role (id, name) values (255, 'Project Manager');
insert into role (id, name) values (256, 'Project Manager');
insert into role (id, name) values (257, 'Architect');
insert into role (id, name) values (258, 'Construction Worker');
insert into role (id, name) values (259, 'Subcontractor');
insert into role (id, name) values (260, 'Project Manager');
insert into role (id, name) values (261, 'Surveyor');
insert into role (id, name) values (262, 'Project Manager');
insert into role (id, name) values (263, 'Architect');
insert into role (id, name) values (264, 'Construction Manager');
insert into role (id, name) values (265, 'Subcontractor');
insert into role (id, name) values (266, 'Project Manager');
insert into role (id, name) values (267, 'Surveyor');
insert into role (id, name) values (268, 'Architect');
insert into role (id, name) values (269, 'Architect');
insert into role (id, name) values (270, 'Estimator');
insert into role (id, name) values (271, 'Project Manager');
insert into role (id, name) values (272, 'Engineer');
insert into role (id, name) values (273, 'Construction Worker');
insert into role (id, name) values (274, 'Estimator');
insert into role (id, name) values (275, 'Project Manager');
insert into role (id, name) values (276, 'Supervisor');
insert into role (id, name) values (277, 'Engineer');
insert into role (id, name) values (278, 'Electrician');
insert into role (id, name) values (279, 'Electrician');
insert into role (id, name) values (280, 'Subcontractor');
insert into role (id, name) values (281, 'Construction Worker');
insert into role (id, name) values (282, 'Construction Worker');
insert into role (id, name) values (283, 'Construction Expeditor');
insert into role (id, name) values (284, 'Construction Manager');
insert into role (id, name) values (285, 'Subcontractor');
insert into role (id, name) values (286, 'Supervisor');
insert into role (id, name) values (287, 'Project Manager');
insert into role (id, name) values (288, 'Engineer');
insert into role (id, name) values (289, 'Architect');
insert into role (id, name) values (290, 'Project Manager');
insert into role (id, name) values (291, 'Construction Expeditor');
insert into role (id, name) values (292, 'Supervisor');
insert into role (id, name) values (293, 'Construction Foreman');
insert into role (id, name) values (294, 'Supervisor');
insert into role (id, name) values (295, 'Engineer');
insert into role (id, name) values (296, 'Project Manager');
insert into role (id, name) values (297, 'Construction Manager');
insert into role (id, name) values (298, 'Project Manager');
insert into role (id, name) values (299, 'Surveyor');
insert into role (id, name) values (300, 'Construction Worker');
insert into role (id, name) values (301, 'Subcontractor');
insert into role (id, name) values (302, 'Supervisor');
insert into role (id, name) values (303, 'Construction Manager');
insert into role (id, name) values (304, 'Construction Expeditor');
insert into role (id, name) values (305, 'Construction Foreman');
insert into role (id, name) values (306, 'Supervisor');
insert into role (id, name) values (307, 'Construction Worker');
insert into role (id, name) values (308, 'Subcontractor');
insert into role (id, name) values (309, 'Construction Expeditor');
insert into role (id, name) values (310, 'Construction Worker');
insert into role (id, name) values (311, 'Supervisor');
insert into role (id, name) values (312, 'Subcontractor');
insert into role (id, name) values (313, 'Supervisor');
insert into role (id, name) values (314, 'Construction Expeditor');
insert into role (id, name) values (315, 'Project Manager');
insert into role (id, name) values (316, 'Project Manager');
insert into role (id, name) values (317, 'Supervisor');
insert into role (id, name) values (318, 'Construction Expeditor');
insert into role (id, name) values (319, 'Engineer');
insert into role (id, name) values (320, 'Project Manager');
insert into role (id, name) values (321, 'Construction Foreman');
insert into role (id, name) values (322, 'Construction Worker');
insert into role (id, name) values (323, 'Construction Foreman');
insert into role (id, name) values (324, 'Construction Expeditor');
insert into role (id, name) values (325, 'Architect');
insert into role (id, name) values (326, 'Construction Expeditor');
insert into role (id, name) values (327, 'Construction Manager');
insert into role (id, name) values (328, 'Estimator');
insert into role (id, name) values (329, 'Engineer');
insert into role (id, name) values (330, 'Supervisor');
insert into role (id, name) values (331, 'Surveyor');
insert into role (id, name) values (332, 'Construction Manager');
insert into role (id, name) values (333, 'Engineer');
insert into role (id, name) values (334, 'Estimator');
insert into role (id, name) values (335, 'Engineer');
insert into role (id, name) values (336, 'Construction Expeditor');
insert into role (id, name) values (337, 'Construction Expeditor');
insert into role (id, name) values (338, 'Estimator');
insert into role (id, name) values (339, 'Construction Expeditor');
insert into role (id, name) values (340, 'Construction Worker');
insert into role (id, name) values (341, 'Architect');
insert into role (id, name) values (342, 'Construction Worker');
insert into role (id, name) values (343, 'Construction Foreman');
insert into role (id, name) values (344, 'Construction Worker');
insert into role (id, name) values (345, 'Construction Worker');
insert into role (id, name) values (346, 'Architect');
insert into role (id, name) values (347, 'Subcontractor');
insert into role (id, name) values (348, 'Electrician');
insert into role (id, name) values (349, 'Supervisor');
insert into role (id, name) values (350, 'Estimator');
insert into role (id, name) values (351, 'Construction Manager');
insert into role (id, name) values (352, 'Architect');
insert into role (id, name) values (353, 'Engineer');
insert into role (id, name) values (354, 'Architect');
insert into role (id, name) values (355, 'Engineer');
insert into role (id, name) values (356, 'Construction Worker');
insert into role (id, name) values (357, 'Estimator');
insert into role (id, name) values (358, 'Supervisor');
insert into role (id, name) values (359, 'Construction Manager');
insert into role (id, name) values (360, 'Surveyor');
insert into role (id, name) values (361, 'Construction Manager');
insert into role (id, name) values (362, 'Construction Foreman');
insert into role (id, name) values (363, 'Construction Worker');
insert into role (id, name) values (364, 'Subcontractor');
insert into role (id, name) values (365, 'Estimator');
insert into role (id, name) values (366, 'Architect');
insert into role (id, name) values (367, 'Supervisor');
insert into role (id, name) values (368, 'Electrician');
insert into role (id, name) values (369, 'Architect');
insert into role (id, name) values (370, 'Electrician');
insert into role (id, name) values (371, 'Supervisor');
insert into role (id, name) values (372, 'Subcontractor');
insert into role (id, name) values (373, 'Project Manager');
insert into role (id, name) values (374, 'Supervisor');
insert into role (id, name) values (375, 'Estimator');
insert into role (id, name) values (376, 'Construction Manager');
insert into role (id, name) values (377, 'Engineer');
insert into role (id, name) values (378, 'Engineer');
insert into role (id, name) values (379, 'Construction Manager');
insert into role (id, name) values (380, 'Surveyor');
insert into role (id, name) values (381, 'Electrician');
insert into role (id, name) values (382, 'Construction Expeditor');
insert into role (id, name) values (383, 'Project Manager');
insert into role (id, name) values (384, 'Project Manager');
insert into role (id, name) values (385, 'Estimator');
insert into role (id, name) values (386, 'Subcontractor');
insert into role (id, name) values (387, 'Engineer');
insert into role (id, name) values (388, 'Surveyor');
insert into role (id, name) values (389, 'Construction Manager');
insert into role (id, name) values (390, 'Supervisor');
insert into role (id, name) values (391, 'Surveyor');
insert into role (id, name) values (392, 'Architect');
insert into role (id, name) values (393, 'Surveyor');
insert into role (id, name) values (394, 'Engineer');
insert into role (id, name) values (395, 'Construction Foreman');
insert into role (id, name) values (396, 'Project Manager');
insert into role (id, name) values (397, 'Project Manager');
insert into role (id, name) values (398, 'Surveyor');
insert into role (id, name) values (399, 'Construction Manager');
insert into role (id, name) values (400, 'Construction Worker');
insert into role (id, name) values (401, 'Electrician');
insert into role (id, name) values (402, 'Supervisor');
insert into role (id, name) values (403, 'Architect');
insert into role (id, name) values (404, 'Surveyor');
insert into role (id, name) values (405, 'Subcontractor');
insert into role (id, name) values (406, 'Architect');
insert into role (id, name) values (407, 'Estimator');
insert into role (id, name) values (408, 'Supervisor');
insert into role (id, name) values (409, 'Construction Expeditor');
insert into role (id, name) values (410, 'Architect');
insert into role (id, name) values (411, 'Construction Worker');
insert into role (id, name) values (412, 'Architect');
insert into role (id, name) values (413, 'Construction Expeditor');
insert into role (id, name) values (414, 'Subcontractor');
insert into role (id, name) values (415, 'Project Manager');
insert into role (id, name) values (416, 'Construction Worker');
insert into role (id, name) values (417, 'Construction Manager');
insert into role (id, name) values (418, 'Electrician');
insert into role (id, name) values (419, 'Surveyor');
insert into role (id, name) values (420, 'Project Manager');
insert into role (id, name) values (421, 'Project Manager');
insert into role (id, name) values (422, 'Construction Foreman');
insert into role (id, name) values (423, 'Construction Worker');
insert into role (id, name) values (424, 'Construction Manager');
insert into role (id, name) values (425, 'Supervisor');
insert into role (id, name) values (426, 'Supervisor');
insert into role (id, name) values (427, 'Project Manager');
insert into role (id, name) values (428, 'Electrician');
insert into role (id, name) values (429, 'Construction Expeditor');
insert into role (id, name) values (430, 'Project Manager');
insert into role (id, name) values (431, 'Subcontractor');
insert into role (id, name) values (432, 'Construction Manager');
insert into role (id, name) values (433, 'Construction Manager');
insert into role (id, name) values (434, 'Subcontractor');
insert into role (id, name) values (435, 'Construction Foreman');
insert into role (id, name) values (436, 'Construction Worker');
insert into role (id, name) values (437, 'Construction Worker');
insert into role (id, name) values (438, 'Construction Manager');
insert into role (id, name) values (439, 'Construction Worker');
insert into role (id, name) values (440, 'Supervisor');
insert into role (id, name) values (441, 'Construction Manager');
insert into role (id, name) values (442, 'Supervisor');
insert into role (id, name) values (443, 'Supervisor');
insert into role (id, name) values (444, 'Construction Worker');
insert into role (id, name) values (445, 'Construction Foreman');
insert into role (id, name) values (446, 'Engineer');
insert into role (id, name) values (447, 'Estimator');
insert into role (id, name) values (448, 'Construction Manager');
insert into role (id, name) values (449, 'Subcontractor');
insert into role (id, name) values (450, 'Project Manager');
insert into role (id, name) values (451, 'Subcontractor');
insert into role (id, name) values (452, 'Electrician');
insert into role (id, name) values (453, 'Surveyor');
insert into role (id, name) values (454, 'Construction Expeditor');
insert into role (id, name) values (455, 'Subcontractor');
insert into role (id, name) values (456, 'Project Manager');
insert into role (id, name) values (457, 'Construction Foreman');
insert into role (id, name) values (458, 'Engineer');
insert into role (id, name) values (459, 'Engineer');
insert into role (id, name) values (460, 'Construction Expeditor');
insert into role (id, name) values (461, 'Construction Expeditor');
insert into role (id, name) values (462, 'Subcontractor');
insert into role (id, name) values (463, 'Subcontractor');
insert into role (id, name) values (464, 'Construction Expeditor');
insert into role (id, name) values (465, 'Construction Foreman');
insert into role (id, name) values (466, 'Estimator');
insert into role (id, name) values (467, 'Surveyor');
insert into role (id, name) values (468, 'Construction Foreman');
insert into role (id, name) values (469, 'Subcontractor');
insert into role (id, name) values (470, 'Project Manager');
insert into role (id, name) values (471, 'Estimator');
insert into role (id, name) values (472, 'Surveyor');
insert into role (id, name) values (473, 'Architect');
insert into role (id, name) values (474, 'Engineer');
insert into role (id, name) values (475, 'Construction Manager');
insert into role (id, name) values (476, 'Engineer');
insert into role (id, name) values (477, 'Supervisor');
insert into role (id, name) values (478, 'Construction Expeditor');
insert into role (id, name) values (479, 'Construction Expeditor');
insert into role (id, name) values (480, 'Electrician');
insert into role (id, name) values (481, 'Electrician');
insert into role (id, name) values (482, 'Surveyor');
insert into role (id, name) values (483, 'Project Manager');
insert into role (id, name) values (484, 'Construction Foreman');
insert into role (id, name) values (485, 'Engineer');
insert into role (id, name) values (486, 'Construction Foreman');
insert into role (id, name) values (487, 'Engineer');
insert into role (id, name) values (488, 'Construction Foreman');
insert into role (id, name) values (489, 'Construction Manager');
insert into role (id, name) values (490, 'Project Manager');
insert into role (id, name) values (491, 'Surveyor');
insert into role (id, name) values (492, 'Estimator');
insert into role (id, name) values (493, 'Construction Worker');
insert into role (id, name) values (494, 'Estimator');
insert into role (id, name) values (495, 'Project Manager');
insert into role (id, name) values (496, 'Construction Foreman');
insert into role (id, name) values (497, 'Engineer');
insert into role (id, name) values (498, 'Construction Expeditor');
insert into role (id, name) values (499, 'Electrician');
insert into role (id, name) values (500, 'Supervisor');
insert into role (id, name) values (501, 'Engineer');
insert into role (id, name) values (502, 'Project Manager');
insert into role (id, name) values (503, 'Surveyor');
insert into role (id, name) values (504, 'Surveyor');
insert into role (id, name) values (505, 'Construction Expeditor');
insert into role (id, name) values (506, 'Construction Manager');
insert into role (id, name) values (507, 'Engineer');
insert into role (id, name) values (508, 'Subcontractor');
insert into role (id, name) values (509, 'Construction Worker');
insert into role (id, name) values (510, 'Architect');
insert into role (id, name) values (511, 'Surveyor');
insert into role (id, name) values (512, 'Estimator');
insert into role (id, name) values (513, 'Construction Worker');
insert into role (id, name) values (514, 'Engineer');
insert into role (id, name) values (515, 'Project Manager');
insert into role (id, name) values (516, 'Supervisor');
insert into role (id, name) values (517, 'Construction Worker');
insert into role (id, name) values (518, 'Construction Worker');
insert into role (id, name) values (519, 'Construction Manager');
insert into role (id, name) values (520, 'Supervisor');
insert into role (id, name) values (521, 'Construction Manager');
insert into role (id, name) values (522, 'Construction Expeditor');
insert into role (id, name) values (523, 'Construction Expeditor');
insert into role (id, name) values (524, 'Estimator');
insert into role (id, name) values (525, 'Electrician');
insert into role (id, name) values (526, 'Engineer');
insert into role (id, name) values (527, 'Electrician');
insert into role (id, name) values (528, 'Project Manager');
insert into role (id, name) values (529, 'Electrician');
insert into role (id, name) values (530, 'Construction Worker');
insert into role (id, name) values (531, 'Construction Foreman');
insert into role (id, name) values (532, 'Engineer');
insert into role (id, name) values (533, 'Surveyor');
insert into role (id, name) values (534, 'Estimator');
insert into role (id, name) values (535, 'Engineer');
insert into role (id, name) values (536, 'Engineer');
insert into role (id, name) values (537, 'Construction Foreman');
insert into role (id, name) values (538, 'Architect');
insert into role (id, name) values (539, 'Supervisor');
insert into role (id, name) values (540, 'Construction Foreman');
insert into role (id, name) values (541, 'Architect');
insert into role (id, name) values (542, 'Construction Expeditor');
insert into role (id, name) values (543, 'Subcontractor');
insert into role (id, name) values (544, 'Estimator');
insert into role (id, name) values (545, 'Project Manager');
insert into role (id, name) values (546, 'Supervisor');
insert into role (id, name) values (547, 'Electrician');
insert into role (id, name) values (548, 'Project Manager');
insert into role (id, name) values (549, 'Supervisor');
insert into role (id, name) values (550, 'Construction Manager');
insert into role (id, name) values (551, 'Construction Worker');
insert into role (id, name) values (552, 'Construction Manager');
insert into role (id, name) values (553, 'Project Manager');
insert into role (id, name) values (554, 'Construction Foreman');
insert into role (id, name) values (555, 'Electrician');
insert into role (id, name) values (556, 'Project Manager');
insert into role (id, name) values (557, 'Construction Foreman');
insert into role (id, name) values (558, 'Project Manager');
insert into role (id, name) values (559, 'Supervisor');
insert into role (id, name) values (560, 'Construction Worker');
insert into role (id, name) values (561, 'Electrician');
insert into role (id, name) values (562, 'Supervisor');
insert into role (id, name) values (563, 'Subcontractor');
insert into role (id, name) values (564, 'Construction Manager');
insert into role (id, name) values (565, 'Supervisor');
insert into role (id, name) values (566, 'Estimator');
insert into role (id, name) values (567, 'Supervisor');
insert into role (id, name) values (568, 'Construction Manager');
insert into role (id, name) values (569, 'Subcontractor');
insert into role (id, name) values (570, 'Supervisor');
insert into role (id, name) values (571, 'Construction Worker');
insert into role (id, name) values (572, 'Construction Expeditor');
insert into role (id, name) values (573, 'Construction Worker');
insert into role (id, name) values (574, 'Estimator');
insert into role (id, name) values (575, 'Estimator');
insert into role (id, name) values (576, 'Electrician');
insert into role (id, name) values (577, 'Electrician');
insert into role (id, name) values (578, 'Subcontractor');
insert into role (id, name) values (579, 'Construction Expeditor');
insert into role (id, name) values (580, 'Project Manager');
insert into role (id, name) values (581, 'Construction Foreman');
insert into role (id, name) values (582, 'Engineer');
insert into role (id, name) values (583, 'Construction Expeditor');
insert into role (id, name) values (584, 'Subcontractor');
insert into role (id, name) values (585, 'Construction Foreman');
insert into role (id, name) values (586, 'Surveyor');
insert into role (id, name) values (587, 'Estimator');
insert into role (id, name) values (588, 'Electrician');
insert into role (id, name) values (589, 'Estimator');
insert into role (id, name) values (590, 'Electrician');
insert into role (id, name) values (591, 'Engineer');
insert into role (id, name) values (592, 'Architect');
insert into role (id, name) values (593, 'Construction Worker');
insert into role (id, name) values (594, 'Electrician');
insert into role (id, name) values (595, 'Electrician');
insert into role (id, name) values (596, 'Supervisor');
insert into role (id, name) values (597, 'Architect');
insert into role (id, name) values (598, 'Construction Worker');
insert into role (id, name) values (599, 'Engineer');
insert into role (id, name) values (600, 'Construction Manager');
insert into role (id, name) values (601, 'Surveyor');
insert into role (id, name) values (602, 'Construction Expeditor');
insert into role (id, name) values (603, 'Estimator');
insert into role (id, name) values (604, 'Electrician');
insert into role (id, name) values (605, 'Project Manager');
insert into role (id, name) values (606, 'Supervisor');
insert into role (id, name) values (607, 'Supervisor');
insert into role (id, name) values (608, 'Construction Worker');
insert into role (id, name) values (609, 'Construction Manager');
insert into role (id, name) values (610, 'Electrician');
insert into role (id, name) values (611, 'Construction Expeditor');
insert into role (id, name) values (612, 'Electrician');
insert into role (id, name) values (613, 'Construction Worker');
insert into role (id, name) values (614, 'Architect');
insert into role (id, name) values (615, 'Construction Foreman');
insert into role (id, name) values (616, 'Construction Worker');
insert into role (id, name) values (617, 'Subcontractor');
insert into role (id, name) values (618, 'Construction Foreman');
insert into role (id, name) values (619, 'Construction Expeditor');
insert into role (id, name) values (620, 'Electrician');
insert into role (id, name) values (621, 'Construction Worker');
insert into role (id, name) values (622, 'Electrician');
insert into role (id, name) values (623, 'Estimator');
insert into role (id, name) values (624, 'Electrician');
insert into role (id, name) values (625, 'Subcontractor');
insert into role (id, name) values (626, 'Electrician');
insert into role (id, name) values (627, 'Subcontractor');
insert into role (id, name) values (628, 'Project Manager');
insert into role (id, name) values (629, 'Architect');
insert into role (id, name) values (630, 'Project Manager');
insert into role (id, name) values (631, 'Construction Worker');
insert into role (id, name) values (632, 'Electrician');
insert into role (id, name) values (633, 'Construction Foreman');
insert into role (id, name) values (634, 'Construction Manager');
insert into role (id, name) values (635, 'Estimator');
insert into role (id, name) values (636, 'Estimator');
insert into role (id, name) values (637, 'Construction Worker');
insert into role (id, name) values (638, 'Project Manager');
insert into role (id, name) values (639, 'Surveyor');
insert into role (id, name) values (640, 'Supervisor');
insert into role (id, name) values (641, 'Construction Manager');
insert into role (id, name) values (642, 'Construction Expeditor');
insert into role (id, name) values (643, 'Project Manager');
insert into role (id, name) values (644, 'Engineer');
insert into role (id, name) values (645, 'Architect');
insert into role (id, name) values (646, 'Project Manager');
insert into role (id, name) values (647, 'Engineer');
insert into role (id, name) values (648, 'Subcontractor');
insert into role (id, name) values (649, 'Construction Foreman');
insert into role (id, name) values (650, 'Supervisor');
insert into role (id, name) values (651, 'Engineer');
insert into role (id, name) values (652, 'Supervisor');
insert into role (id, name) values (653, 'Construction Expeditor');
insert into role (id, name) values (654, 'Construction Foreman');
insert into role (id, name) values (655, 'Electrician');
insert into role (id, name) values (656, 'Construction Worker');
insert into role (id, name) values (657, 'Construction Manager');
insert into role (id, name) values (658, 'Construction Foreman');
insert into role (id, name) values (659, 'Surveyor');
insert into role (id, name) values (660, 'Supervisor');
insert into role (id, name) values (661, 'Construction Expeditor');
insert into role (id, name) values (662, 'Estimator');
insert into role (id, name) values (663, 'Construction Worker');
insert into role (id, name) values (664, 'Supervisor');
insert into role (id, name) values (665, 'Construction Foreman');
insert into role (id, name) values (666, 'Construction Foreman');
insert into role (id, name) values (667, 'Construction Manager');
insert into role (id, name) values (668, 'Engineer');
insert into role (id, name) values (669, 'Surveyor');
insert into role (id, name) values (670, 'Electrician');
insert into role (id, name) values (671, 'Supervisor');
insert into role (id, name) values (672, 'Architect');
insert into role (id, name) values (673, 'Surveyor');
insert into role (id, name) values (674, 'Surveyor');
insert into role (id, name) values (675, 'Subcontractor');
insert into role (id, name) values (676, 'Supervisor');
insert into role (id, name) values (677, 'Construction Expeditor');
insert into role (id, name) values (678, 'Engineer');
insert into role (id, name) values (679, 'Construction Worker');
insert into role (id, name) values (680, 'Estimator');
insert into role (id, name) values (681, 'Surveyor');
insert into role (id, name) values (682, 'Engineer');
insert into role (id, name) values (683, 'Engineer');
insert into role (id, name) values (684, 'Estimator');
insert into role (id, name) values (685, 'Supervisor');
insert into role (id, name) values (686, 'Architect');
insert into role (id, name) values (687, 'Surveyor');
insert into role (id, name) values (688, 'Subcontractor');
insert into role (id, name) values (689, 'Supervisor');
insert into role (id, name) values (690, 'Construction Manager');
insert into role (id, name) values (691, 'Electrician');
insert into role (id, name) values (692, 'Construction Manager');
insert into role (id, name) values (693, 'Electrician');
insert into role (id, name) values (694, 'Subcontractor');
insert into role (id, name) values (695, 'Construction Manager');
insert into role (id, name) values (696, 'Architect');
insert into role (id, name) values (697, 'Electrician');
insert into role (id, name) values (698, 'Supervisor');
insert into role (id, name) values (699, 'Estimator');
insert into role (id, name) values (700, 'Supervisor');
insert into role (id, name) values (701, 'Estimator');
insert into role (id, name) values (702, 'Estimator');
insert into role (id, name) values (703, 'Project Manager');
insert into role (id, name) values (704, 'Construction Foreman');
insert into role (id, name) values (705, 'Construction Foreman');
insert into role (id, name) values (706, 'Construction Worker');
insert into role (id, name) values (707, 'Electrician');
insert into role (id, name) values (708, 'Electrician');
insert into role (id, name) values (709, 'Project Manager');
insert into role (id, name) values (710, 'Construction Foreman');
insert into role (id, name) values (711, 'Estimator');
insert into role (id, name) values (712, 'Construction Foreman');
insert into role (id, name) values (713, 'Construction Worker');
insert into role (id, name) values (714, 'Subcontractor');
insert into role (id, name) values (715, 'Surveyor');
insert into role (id, name) values (716, 'Architect');
insert into role (id, name) values (717, 'Construction Foreman');
insert into role (id, name) values (718, 'Estimator');
insert into role (id, name) values (719, 'Construction Worker');
insert into role (id, name) values (720, 'Construction Worker');
insert into role (id, name) values (721, 'Subcontractor');
insert into role (id, name) values (722, 'Engineer');
insert into role (id, name) values (723, 'Construction Expeditor');
insert into role (id, name) values (724, 'Project Manager');
insert into role (id, name) values (725, 'Supervisor');
insert into role (id, name) values (726, 'Supervisor');
insert into role (id, name) values (727, 'Construction Foreman');
insert into role (id, name) values (728, 'Construction Foreman');
insert into role (id, name) values (729, 'Construction Expeditor');
insert into role (id, name) values (730, 'Construction Foreman');
insert into role (id, name) values (731, 'Construction Worker');
insert into role (id, name) values (732, 'Engineer');
insert into role (id, name) values (733, 'Estimator');
insert into role (id, name) values (734, 'Architect');
insert into role (id, name) values (735, 'Construction Expeditor');
insert into role (id, name) values (736, 'Construction Worker');
insert into role (id, name) values (737, 'Architect');
insert into role (id, name) values (738, 'Surveyor');
insert into role (id, name) values (739, 'Electrician');
insert into role (id, name) values (740, 'Electrician');
insert into role (id, name) values (741, 'Construction Expeditor');
insert into role (id, name) values (742, 'Construction Manager');
insert into role (id, name) values (743, 'Engineer');
insert into role (id, name) values (744, 'Supervisor');
insert into role (id, name) values (745, 'Supervisor');
insert into role (id, name) values (746, 'Project Manager');
insert into role (id, name) values (747, 'Engineer');
insert into role (id, name) values (748, 'Surveyor');
insert into role (id, name) values (749, 'Construction Foreman');
insert into role (id, name) values (750, 'Electrician');
insert into role (id, name) values (751, 'Engineer');
insert into role (id, name) values (752, 'Construction Manager');
insert into role (id, name) values (753, 'Construction Manager');
insert into role (id, name) values (754, 'Project Manager');
insert into role (id, name) values (755, 'Electrician');
insert into role (id, name) values (756, 'Estimator');
insert into role (id, name) values (757, 'Surveyor');
insert into role (id, name) values (758, 'Electrician');
insert into role (id, name) values (759, 'Estimator');
insert into role (id, name) values (760, 'Surveyor');
insert into role (id, name) values (761, 'Electrician');
insert into role (id, name) values (762, 'Estimator');
insert into role (id, name) values (763, 'Engineer');
insert into role (id, name) values (764, 'Construction Worker');
insert into role (id, name) values (765, 'Construction Expeditor');
insert into role (id, name) values (766, 'Engineer');
insert into role (id, name) values (767, 'Electrician');
insert into role (id, name) values (768, 'Project Manager');
insert into role (id, name) values (769, 'Surveyor');
insert into role (id, name) values (770, 'Construction Expeditor');
insert into role (id, name) values (771, 'Architect');
insert into role (id, name) values (772, 'Surveyor');
insert into role (id, name) values (773, 'Supervisor');
insert into role (id, name) values (774, 'Electrician');
insert into role (id, name) values (775, 'Subcontractor');
insert into role (id, name) values (776, 'Estimator');
insert into role (id, name) values (777, 'Architect');
insert into role (id, name) values (778, 'Supervisor');
insert into role (id, name) values (779, 'Construction Worker');
insert into role (id, name) values (780, 'Electrician');
insert into role (id, name) values (781, 'Construction Worker');
insert into role (id, name) values (782, 'Architect');
insert into role (id, name) values (783, 'Supervisor');
insert into role (id, name) values (784, 'Estimator');
insert into role (id, name) values (785, 'Architect');
insert into role (id, name) values (786, 'Electrician');
insert into role (id, name) values (787, 'Construction Foreman');
insert into role (id, name) values (788, 'Construction Expeditor');
insert into role (id, name) values (789, 'Construction Manager');
insert into role (id, name) values (790, 'Construction Foreman');
insert into role (id, name) values (791, 'Supervisor');
insert into role (id, name) values (792, 'Supervisor');
insert into role (id, name) values (793, 'Construction Foreman');
insert into role (id, name) values (794, 'Estimator');
insert into role (id, name) values (795, 'Construction Expeditor');
insert into role (id, name) values (796, 'Project Manager');
insert into role (id, name) values (797, 'Construction Worker');
insert into role (id, name) values (798, 'Electrician');
insert into role (id, name) values (799, 'Construction Foreman');
insert into role (id, name) values (800, 'Supervisor');
insert into role (id, name) values (801, 'Architect');
insert into role (id, name) values (802, 'Construction Expeditor');
insert into role (id, name) values (803, 'Electrician');
insert into role (id, name) values (804, 'Surveyor');
insert into role (id, name) values (805, 'Estimator');
insert into role (id, name) values (806, 'Supervisor');
insert into role (id, name) values (807, 'Construction Expeditor');
insert into role (id, name) values (808, 'Surveyor');
insert into role (id, name) values (809, 'Construction Manager');
insert into role (id, name) values (810, 'Construction Manager');
insert into role (id, name) values (811, 'Surveyor');
insert into role (id, name) values (812, 'Estimator');
insert into role (id, name) values (813, 'Project Manager');
insert into role (id, name) values (814, 'Architect');
insert into role (id, name) values (815, 'Construction Expeditor');
insert into role (id, name) values (816, 'Electrician');
insert into role (id, name) values (817, 'Project Manager');
insert into role (id, name) values (818, 'Engineer');
insert into role (id, name) values (819, 'Construction Foreman');
insert into role (id, name) values (820, 'Construction Worker');
insert into role (id, name) values (821, 'Estimator');
insert into role (id, name) values (822, 'Construction Foreman');
insert into role (id, name) values (823, 'Estimator');
insert into role (id, name) values (824, 'Construction Worker');
insert into role (id, name) values (825, 'Supervisor');
insert into role (id, name) values (826, 'Construction Expeditor');
insert into role (id, name) values (827, 'Supervisor');
insert into role (id, name) values (828, 'Architect');
insert into role (id, name) values (829, 'Construction Manager');
insert into role (id, name) values (830, 'Engineer');
insert into role (id, name) values (831, 'Construction Manager');
insert into role (id, name) values (832, 'Construction Expeditor');
insert into role (id, name) values (833, 'Project Manager');
insert into role (id, name) values (834, 'Construction Expeditor');
insert into role (id, name) values (835, 'Construction Worker');
insert into role (id, name) values (836, 'Electrician');
insert into role (id, name) values (837, 'Architect');
insert into role (id, name) values (838, 'Construction Foreman');
insert into role (id, name) values (839, 'Electrician');
insert into role (id, name) values (840, 'Construction Worker');
insert into role (id, name) values (841, 'Subcontractor');
insert into role (id, name) values (842, 'Project Manager');
insert into role (id, name) values (843, 'Construction Worker');
insert into role (id, name) values (844, 'Construction Manager');
insert into role (id, name) values (845, 'Surveyor');
insert into role (id, name) values (846, 'Construction Manager');
insert into role (id, name) values (847, 'Supervisor');
insert into role (id, name) values (848, 'Electrician');
insert into role (id, name) values (849, 'Construction Manager');
insert into role (id, name) values (850, 'Subcontractor');
insert into role (id, name) values (851, 'Architect');
insert into role (id, name) values (852, 'Construction Expeditor');
insert into role (id, name) values (853, 'Construction Manager');
insert into role (id, name) values (854, 'Subcontractor');
insert into role (id, name) values (855, 'Engineer');
insert into role (id, name) values (856, 'Architect');
insert into role (id, name) values (857, 'Construction Foreman');
insert into role (id, name) values (858, 'Project Manager');
insert into role (id, name) values (859, 'Electrician');
insert into role (id, name) values (860, 'Architect');
insert into role (id, name) values (861, 'Project Manager');
insert into role (id, name) values (862, 'Engineer');
insert into role (id, name) values (863, 'Supervisor');
insert into role (id, name) values (864, 'Architect');
insert into role (id, name) values (865, 'Architect');
insert into role (id, name) values (866, 'Construction Worker');
insert into role (id, name) values (867, 'Construction Expeditor');
insert into role (id, name) values (868, 'Construction Manager');
insert into role (id, name) values (869, 'Architect');
insert into role (id, name) values (870, 'Construction Worker');
insert into role (id, name) values (871, 'Construction Manager');
insert into role (id, name) values (872, 'Project Manager');
insert into role (id, name) values (873, 'Construction Expeditor');
insert into role (id, name) values (874, 'Electrician');
insert into role (id, name) values (875, 'Engineer');
insert into role (id, name) values (876, 'Architect');
insert into role (id, name) values (877, 'Engineer');
insert into role (id, name) values (878, 'Supervisor');
insert into role (id, name) values (879, 'Surveyor');
insert into role (id, name) values (880, 'Architect');
insert into role (id, name) values (881, 'Construction Expeditor');
insert into role (id, name) values (882, 'Estimator');
insert into role (id, name) values (883, 'Engineer');
insert into role (id, name) values (884, 'Construction Expeditor');
insert into role (id, name) values (885, 'Construction Expeditor');
insert into role (id, name) values (886, 'Architect');
insert into role (id, name) values (887, 'Surveyor');
insert into role (id, name) values (888, 'Construction Foreman');
insert into role (id, name) values (889, 'Construction Expeditor');
insert into role (id, name) values (890, 'Construction Expeditor');
insert into role (id, name) values (891, 'Engineer');
insert into role (id, name) values (892, 'Surveyor');
insert into role (id, name) values (893, 'Architect');
insert into role (id, name) values (894, 'Estimator');
insert into role (id, name) values (895, 'Architect');
insert into role (id, name) values (896, 'Construction Manager');
insert into role (id, name) values (897, 'Supervisor');
insert into role (id, name) values (898, 'Construction Foreman');
insert into role (id, name) values (899, 'Construction Expeditor');
insert into role (id, name) values (900, 'Project Manager');
insert into role (id, name) values (901, 'Construction Expeditor');
insert into role (id, name) values (902, 'Construction Manager');
insert into role (id, name) values (903, 'Construction Expeditor');
insert into role (id, name) values (904, 'Project Manager');
insert into role (id, name) values (905, 'Construction Expeditor');
insert into role (id, name) values (906, 'Construction Manager');
insert into role (id, name) values (907, 'Architect');
insert into role (id, name) values (908, 'Estimator');
insert into role (id, name) values (909, 'Construction Manager');
insert into role (id, name) values (910, 'Surveyor');
insert into role (id, name) values (911, 'Estimator');
insert into role (id, name) values (912, 'Supervisor');
insert into role (id, name) values (913, 'Construction Worker');
insert into role (id, name) values (914, 'Supervisor');
insert into role (id, name) values (915, 'Estimator');
insert into role (id, name) values (916, 'Subcontractor');
insert into role (id, name) values (917, 'Architect');
insert into role (id, name) values (918, 'Estimator');
insert into role (id, name) values (919, 'Surveyor');
insert into role (id, name) values (920, 'Architect');
insert into role (id, name) values (921, 'Construction Worker');
insert into role (id, name) values (922, 'Construction Worker');
insert into role (id, name) values (923, 'Subcontractor');
insert into role (id, name) values (924, 'Engineer');
insert into role (id, name) values (925, 'Supervisor');
insert into role (id, name) values (926, 'Electrician');
insert into role (id, name) values (927, 'Construction Worker');
insert into role (id, name) values (928, 'Construction Manager');
insert into role (id, name) values (929, 'Surveyor');
insert into role (id, name) values (930, 'Project Manager');
insert into role (id, name) values (931, 'Construction Worker');
insert into role (id, name) values (932, 'Engineer');
insert into role (id, name) values (933, 'Subcontractor');
insert into role (id, name) values (934, 'Construction Worker');
insert into role (id, name) values (935, 'Construction Expeditor');
insert into role (id, name) values (936, 'Surveyor');
insert into role (id, name) values (937, 'Estimator');
insert into role (id, name) values (938, 'Surveyor');
insert into role (id, name) values (939, 'Electrician');
insert into role (id, name) values (940, 'Construction Expeditor');
insert into role (id, name) values (941, 'Construction Foreman');
insert into role (id, name) values (942, 'Subcontractor');
insert into role (id, name) values (943, 'Surveyor');
insert into role (id, name) values (944, 'Architect');
insert into role (id, name) values (945, 'Project Manager');
insert into role (id, name) values (946, 'Estimator');
insert into role (id, name) values (947, 'Subcontractor');
insert into role (id, name) values (948, 'Construction Foreman');
insert into role (id, name) values (949, 'Project Manager');
insert into role (id, name) values (950, 'Estimator');
insert into role (id, name) values (951, 'Estimator');
insert into role (id, name) values (952, 'Project Manager');
insert into role (id, name) values (953, 'Supervisor');
insert into role (id, name) values (954, 'Project Manager');
insert into role (id, name) values (955, 'Engineer');
insert into role (id, name) values (956, 'Engineer');
insert into role (id, name) values (957, 'Electrician');
insert into role (id, name) values (958, 'Surveyor');
insert into role (id, name) values (959, 'Supervisor');
insert into role (id, name) values (960, 'Architect');
insert into role (id, name) values (961, 'Architect');
insert into role (id, name) values (962, 'Construction Manager');
insert into role (id, name) values (963, 'Construction Foreman');
insert into role (id, name) values (964, 'Subcontractor');
insert into role (id, name) values (965, 'Supervisor');
insert into role (id, name) values (966, 'Construction Manager');
insert into role (id, name) values (967, 'Surveyor');
insert into role (id, name) values (968, 'Project Manager');
insert into role (id, name) values (969, 'Supervisor');
insert into role (id, name) values (970, 'Electrician');
insert into role (id, name) values (971, 'Architect');
insert into role (id, name) values (972, 'Construction Worker');
insert into role (id, name) values (973, 'Electrician');
insert into role (id, name) values (974, 'Subcontractor');
insert into role (id, name) values (975, 'Construction Worker');
insert into role (id, name) values (976, 'Construction Expeditor');
insert into role (id, name) values (977, 'Supervisor');
insert into role (id, name) values (978, 'Project Manager');
insert into role (id, name) values (979, 'Surveyor');
insert into role (id, name) values (980, 'Architect');
insert into role (id, name) values (981, 'Engineer');
insert into role (id, name) values (982, 'Electrician');
insert into role (id, name) values (983, 'Architect');
insert into role (id, name) values (984, 'Construction Manager');
insert into role (id, name) values (985, 'Construction Expeditor');
insert into role (id, name) values (986, 'Estimator');
insert into role (id, name) values (987, 'Construction Foreman');
insert into role (id, name) values (988, 'Electrician');
insert into role (id, name) values (989, 'Construction Foreman');
insert into role (id, name) values (990, 'Supervisor');
insert into role (id, name) values (991, 'Supervisor');
insert into role (id, name) values (992, 'Estimator');
insert into role (id, name) values (993, 'Construction Expeditor');
insert into role (id, name) values (994, 'Construction Manager');
insert into role (id, name) values (995, 'Construction Foreman');
insert into role (id, name) values (996, 'Surveyor');
insert into role (id, name) values (997, 'Supervisor');
insert into role (id, name) values (998, 'Electrician');
insert into role (id, name) values (999, 'Supervisor');
insert into role (id, name) values (1000, 'Construction Worker');
