DROP TABLE IF EXISTS tool;
CREATE TABLE tool (
	id INT AUTO_INCREMENT NOT NULL,
	name VARCHAR(50) UNIQUE NOT NULL,
	category_id INT NOT NULL,
	image VARCHAR(50) NULL,
	stock_total INT NOT NULL DEFAULT 0,
	stock_actual INT NOT NULL DEFAULT 0,
	is_active TINYINT(1) NOT NULL DEFAULT 1,

    PRIMARY KEY(id),
    FOREIGN KEY(category_id) REFERENCES category(id)
);
